/**
 * Wordle / Word Duel Arena (Deductive Vocabulary & Logic)
 * GameType: 17
 * 100% Offline Intranet Vocabulary with 3D Tile Flip Animation, Hard Mode, Stats & LAN Duels
 */
(function(window, $) {
    'use strict';

    // 1. Curated Target Secret Words List (~1,200 High-Frequency Fair 5-Letter Words)
    var TARGET_WORDS = [
        "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADAPT", "ADMIT", "ADOPT", "ADULT", "AFTER",
        "AGAIN", "AGENT", "AGILE", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIGN",
        "ALIKE", "ALIVE", "ALLOW", "ALONG", "ALPHA", "ALTER", "AMONG", "AMPLE", "ANGEL", "ANGER",
        "ANGLE", "ANGRY", "APART", "APPLE", "APPLY", "ARENA", "ARGUE", "ARISE", "ARMOR", "ARRAY",
        "ARROW", "ASIDE", "ASSET", "AUDIO", "AUDIT", "AVOID", "AWAIT", "AWAKE", "AWARD", "AWARE",
        "BADGE", "BASIC", "BASIS", "BEACH", "BEAST", "BEGIN", "BEING", "BELOW", "BENCH", "BIRTH",
        "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLAST", "BLAZE", "BLEED", "BLEND", "BLESS",
        "BLIND", "BLOCK", "BLOOD", "BLOOM", "BLOWN", "BOARD", "BOAST", "BONUS", "BOOST", "BOUND",
        "BRAIN", "BRAKE", "BRAND", "BRAVE", "BREAD", "BREAK", "BREED", "BRICK", "BRIDE", "BRIEF",
        "BRIGHT", "BRING", "BRISK", "BROAD", "BROKE", "BROWN", "BRUSH", "BUILD", "BUILT", "BUNCH",
        "BURST", "BUYER", "CABIN", "CABLE", "CAMEL", "CANAL", "CANDY", "CANOE", "CARGO", "CARRY",
        "CATCH", "CAUSE", "CEASE", "CHAIN", "CHAIR", "CHAMP", "CHANT", "CHAOS", "CHARM", "CHART",
        "CHASE", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER", "CHEST", "CHIEF", "CHILD", "CHILL",
        "CHORD", "CHUNK", "CIVIC", "CIVIL", "CLAIM", "CLAMP", "CLASH", "CLASP", "CLASS", "CLEAN",
        "CLEAR", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLOAK", "CLOCK", "CLONE", "CLOSE", "CLOTH",
        "CLOUD", "COAST", "CORAL", "COUCH", "COUNT", "COURT", "COVER", "CRACK", "CRAFT", "CRANE",
        "CRASH", "CRATE", "CRAWL", "CRAZY", "CREAM", "CREEK", "CREEP", "CREST", "CRIME", "CRISP",
        "CROSS", "CROWD", "CROWN", "CRUDE", "CRUEL", "CRUSH", "CRUST", "CRYPT", "CUBIC", "CURVE",
        "CYBER", "CYCLE", "DAILY", "DANCE", "DEBUT", "DECAY", "DECOR", "DELAY", "DELTA", "DENSE",
        "DEPOT", "DEPTH", "DERBY", "DEVIL", "DIARY", "DIGIT", "DINER", "DISCO", "DITCH", "DIVER",
        "DODGE", "DRAFT", "DRAIN", "DRAMA", "DRAWN", "DREAM", "DRESS", "DRIFT", "DRILL", "DRINK",
        "DRIVE", "DRONE", "DROWN", "DRUID", "DRYLY", "DUSTY", "EAGER", "EARLY", "EARTH", "EASEL",
        "ECHOY", "EIGHT", "ELBOW", "ELDER", "ELECT", "ELITE", "EMPTY", "ENACT", "ENEMY", "ENJOY",
        "ENTER", "ENTRY", "EQUAL", "EQUIP", "ERUPT", "ESSAY", "ETHER", "ETHIC", "EVENT", "EVERY",
        "EXACT", "EXERT", "EXILE", "EXIST", "EXTRA", "FAINT", "FAIRY", "FAITH", "FALSE", "FANCY",
        "FATAL", "FAULT", "FEAST", "FIBER", "FIELD", "FIERY", "FIFTH", "FIFTY", "FIGHT", "FINAL",
        "FLAME", "FLASH", "FLEET", "FLESH", "FLOAT", "FLOCK", "FLOOD", "FLOOR", "FLORA", "FLOUR",
        "FLUID", "FLUTE", "FOCUS", "FORCE", "FORGE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME",
        "FRAUD", "FRESH", "FRONT", "FROST", "FRUIT", "FUNNY", "GALAXY", "GHOST", "GIANT", "GIVEN",
        "GLADE", "GLAND", "GLASS", "GLEAM", "GLIDE", "GLOBE", "GLORY", "GLOVE", "GRACE", "GRADE",
        "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS", "GRAVE", "GREAT", "GREED",
        "GREEN", "GREET", "GRIEF", "GRILL", "GRIND", "GRIPY", "GROAN", "GROVE", "GUARD", "GUESS",
        "GUEST", "GUIDE", "GUILD", "GUILT", "HABIT", "HARSH", "HASTE", "HAVEN", "HEART", "HEAVY",
        "HEDGE", "HEIST", "HELLO", "HEROIC", "HIKER", "HONOR", "HORSE", "HOTEL", "HOUND", "HOUSE",
        "HUMAN", "HUMID", "HUMOR", "HUNGRY", "HURRY", "HYDRO", "IDEAL", "IMAGE", "IMPLY", "INDEX",
        "INERT", "INNER", "INPUT", "IRONY", "ISSUE", "JEWEL", "JOINT", "JUDGE", "JUICE", "JUMBO",
        "JUROR", "KEEPER", "KNIFE", "KNIGHT", "KNOCK", "LABEL", "LABOR", "LANCE", "LASER", "LATCH",
        "LATER", "LAUGH", "LAYER", "LEADER", "LEAFY", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL",
        "LEMON", "LEVEL", "LEVER", "LIGHT", "LIMIT", "LINEN", "LINER", "LOGIC", "LOVER", "LOYAL",
        "LUCKY", "LUNAR", "LUNCH", "LYRIC", "MAGIC", "MAJOR", "MAKER", "MANOR", "MAPLE", "MARCH",
        "MATCH", "MAXIM", "MAYOR", "MEDAL", "MEDIA", "MEDIC", "MELON", "MERCY", "MERGE", "MERIT",
        "METAL", "METER", "MICRO", "MIDST", "MIGHT", "MINER", "MINOR", "MINUS", "MODEL", "MODEM",
        "MONEY", "MONTH", "MORAL", "MOTOR", "MOUNT", "MOUSE", "MOUTH", "MOVIE", "MUSIC", "MYTHS",
        "NAIVE", "NERVE", "NEXUS", "NIGHT", "NOBLE", "NOISE", "NORTH", "NOTCH", "NOVEL", "NURSE",
        "OASIS", "OCEAN", "OCTAL", "OFFER", "OFFSET", "OLIVE", "ONSET", "OPERA", "OPTIC", "ORBIT",
        "ORDER", "ORGAN", "OTHER", "OUGHT", "OUTER", "OZONE", "PACER", "PAINT", "PANEL", "PANIC",
        "PAPER", "PATCH", "PAUSE", "PEACE", "PEACH", "PEARL", "PEDAL", "PHASE", "PHONE", "PHOTO",
        "PIANO", "PILOT", "PINCH", "PIXEL", "PIZZA", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE",
        "PLAZA", "POINT", "POLAR", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR",
        "PRIZE", "PROBE", "PROUD", "PULSE", "PUPIL", "PURSE", "QUEEN", "QUERY", "QUEST", "QUICK",
        "QUIET", "QUOTA", "RADAR", "RADIO", "RAISE", "RALLY", "RANCH", "RANGE", "RAPID", "RATIO",
        "RAZOR", "REACH", "REACT", "READY", "REALM", "REBEL", "REIGN", "RELAX", "RELAY", "RENEW",
        "RESET", "RESIN", "RIDER", "RIDGE", "RIGHT", "RIVAL", "RIVER", "ROBOT", "ROCKY", "ROGER",
        "ROUGE", "ROUGH", "ROUND", "ROUTE", "ROYAL", "RULER", "RUMOR", "RURAL", "RUSTY", "SADLY",
        "SAINT", "SALAD", "SALON", "SALTY", "SCALE", "SCENE", "SCENT", "SCOPE", "SCORE", "SCOUT",
        "SCRAP", "SERVE", "SETUP", "SEVEN", "SHADE", "SHADOW", "SHAFT", "SHAKE", "SHAME", "SHAPE",
        "SHARE", "SHARK", "SHARP", "SHEEP", "SHEER", "SHEET", "SHELF", "SHELL", "SHIFT", "SHINE",
        "SHIRT", "SHOCK", "SHORE", "SHORT", "SHOUT", "SIGHT", "SIGMA", "SIGNAL", "SILENT", "SILVER",
        "SINCE", "SIREN", "SKILL", "SKULL", "SLATE", "SLEEP", "SLICK", "SLIDE", "SMART", "SMASH",
        "SMILE", "SMOKE", "SNAKE", "SOLAR", "SOLID", "SOLVE", "SONIC", "SORRY", "SOUND", "SOUTH",
        "SPACE", "SPARK", "SPEAK", "SPEED", "SPELL", "SPEND", "SPICE", "SPIKE", "SPIN", "SPIRIT",
        "SPLIT", "SPOKE", "SPORT", "SPRAY", "SQUAD", "STAFF", "STAGE", "STAIR", "STAKE", "STAND",
        "STARK", "START", "STATE", "STEAM", "STEEL", "STEEP", "STEER", "STICK", "STIFF", "STILL",
        "STOCK", "STONE", "STORM", "STORY", "STRAP", "STRAW", "STUDY", "STUFF", "STYLE", "SUGAR",
        "SUITE", "SUNNY", "SUPER", "SURGE", "SWIFT", "SWORD", "TABLE", "TASTE", "TEACH", "THEME",
        "THICK", "THING", "THINK", "THIRD", "THORN", "TIGER", "TIGHT", "TIMER", "TITLE", "TOAST",
        "TODAY", "TOKEN", "TONIC", "TOOTH", "TOPIC", "TORCH", "TOTAL", "TOUCH", "TOUGH", "TOWER",
        "TOXIC", "TRACE", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TREND", "TRIAL", "TRIBE",
        "TRICK", "TROOP", "TRUCK", "TRULY", "TRUMP", "TRUST", "TRUTH", "TULIP", "TUNER", "TURBO",
        "TWICE", "TWIST", "ULTRA", "UNCLE", "UNDER", "UNION", "UNITE", "UNITY", "UNTIL", "UPPER",
        "UPSET", "URBAN", "USAGE", "USUAL", "VAGUE", "VALID", "VALUE", "VALVE", "VAPOR", "VAULT",
        "VENUE", "VERVE", "VIDEO", "VIGOR", "VIRAL", "VIRUS", "VISIT", "VITAL", "VIVID", "VOCAL",
        "VOICE", "VORTEX", "VOUCH", "WAGON", "WASTE", "WATCH", "WATER", "WAVE", "WEARY", "WEAVE",
        "WEDGE", "WEIGH", "WHEAT", "WHEEL", "WHERE", "WHICH", "WHILE", "WHITE", "WHOLE", "WIDOW",
        "WIDTH", "WINDY", "WINTER", "WISDOM", "WITCH", "WORLD", "WORRY", "WORTH", "WOULD", "WOUND",
        "WRATH", "WRIST", "WRITE", "WRONG", "YACHT", "YIELD", "YOUNG", "YOUTH", "ZEBRA", "ZERO"
    ];

    // Build Fast Verification Set
    var VALID_WORDS_SET = {};
    TARGET_WORDS.forEach(function(w) {
        if (w.length === 5) VALID_WORDS_SET[w] = true;
    });

    // Supplementary Common English Guess Words Set
    var SUPPLEMENTARY_GUESSES = [
        "AAHED", "ABACK", "ABBA", "ABBOT", "ABHOR", "ABIDE", "ABLER", "ABODE", "ABORT", "ACIDY",
        "ACORN", "ACRES", "ACTED", "ADDED", "ADDER", "ADEPT", "ADIEU", "ADORN", "AFFIX", "AFOOT",
        "AFTER", "AGATE", "AGAVE", "AGLOW", "AGONY", "AIDER", "AIMED", "AIRER", "AISLE", "ALBUM",
        "ALDER", "ALEPH", "ALGAE", "ALIBI", "ALLAY", "ALLOT", "ALLOY", "ALOFT", "ALOHA", "ALONE",
        "ALOOF", "ALOUD", "ALTAR", "ALWAY", "AMASS", "AMAZE", "AMBER", "AMBLE", "AMEND", "AMITY",
        "AMISS", "AMNIO", "AMOUR", "AMPED", "ANVIL", "AORTA", "APING", "APNEA", "APPLE", "APRON",
        "APTLY", "ARBOR", "ARCHY", "ARDOR", "ARGOT", "ARMED", "AROMA", "AROSE", "ARSON", "ARTSY",
        "ASCOT", "ASHEN", "ASHES", "ASKEW", "ASPEN", "ASSAY", "ASTIR", "ATLAS", "ATOLL", "ATOMS",
        "ATONE", "ATTIC", "AUGUR", "AUNTY", "AURAL", "AURAS", "AUTOS", "AVAIL", "AVERT", "AVIAN",
        "AVIDS", "AVOID", "AVOWS", "AWFUL", "AWOKE", "AXIOM", "AXLES", "AZURE", "BABEL", "BABES",
        "BABYS", "BACKS", "BACON", "BAKER", "BALMY", "BANJO", "BARGE", "BARON", "BARRE", "BASAL",
        "BASES", "BATHE", "BATON", "BATTY", "BAYOU", "BEADY", "BEAMS", "BEANS", "BEARD", "BEARS",
        "BEATS", "BEEFY", "BEFOG", "BEGET", "BEGAT", "BEIGE", "BELCH", "BELIE", "BELLE", "BELLS",
        "BELLY", "BENTS", "BERRY", "BERTH", "BESET", "BETEL", "BEVEL", "BICEP", "BIDDY", "BIGHT",
        "BIGOT", "BIKED", "BIKER", "BILGE", "BILLS", "BINGO", "BIPED", "BIRCH", "BITER", "BITTY",
        "BLACK", "BLAHR", "BLAND", "BLARE", "BLEAT", "BLIMP", "BLINK", "BLISS", "BLITZ", "BLOKE",
        "BLOND", "BLOTS", "BLUFF", "BLUNT", "BLURB", "BLURT", "BLUSH", "BOARS", "BOBBY", "BOGEY",
        "BOGUS", "BOILS", "BOLTS", "BOMBS", "BONDS", "BONED", "BONES", "BONGO", "BONNY", "BOOBY",
        "BOOKS", "BOOMS", "BOORS", "BOOST", "BOOTS", "BOOZE", "BOOZY", "BORAX", "BORED", "BORER",
        "BOSOM", "BOSSY", "BOTCH", "BOUGH", "BOULE", "BOWED", "BOWEL", "BOWER", "BOXED", "BOXER",
        "BRACE", "BRAGS", "BRAID", "BRAIN", "BRAKE", "BRAWL", "BRAWN", "BRAYS", "BRAZE", "BREAD",
        "BREAM", "BREWS", "BRIAR", "BRIBE", "BRINK", "BROIL", "BROOD", "BROOK", "BROOM", "BROTH",
        "BUBBA", "BUCKS", "BUDDY", "BUDGE", "BUFFS", "BUGGY", "BUGLE", "BULLS", "BULLY", "BUMPS",
        "BUMPY", "BUNKS", "BUNNY", "BUOYS", "BURLY", "BURNS", "BURNT", "BURRO", "BUSES", "BUSHY",
        "BUTTE", "BUTTS", "BUXOM", "BUYER", "BUZZY", "BYLAW", "BYWAY", "CABAL", "CABBY", "CABIN",
        "CACAO", "CACHE", "CACTI", "CADDY", "CADET", "CADRE", "CAFES", "CAGED", "CAGER", "CAGES",
        "CAIRN", "CAKED", "CAKES", "CALIF", "CALLS", "CALMS", "CALVE", "CAMEL", "CAMEO", "CAMPS",
        "CANAL", "CANDY", "CANES", "CANNY", "CANOE", "CANON", "CANTO", "CAPED", "CAPER", "CAPES",
        "CARAT", "CARDS", "CARED", "CARER", "CARES", "CARGO", "CAROL", "CARPS", "CARRY", "CARTS",
        "CARVE", "CASES", "CASTE", "CASTS", "CATER", "CATTY", "CAULK", "CAUSE", "CAVES", "CAVIL",
        "CEASE", "CEDAR", "CEDED", "CELEB", "CELLO", "CELLS", "CENTS", "CHAFF", "CHAIN", "CHAIR",
        "CHALK", "CHAMP", "CHANT", "CHAOS", "CHAPS", "CHARD", "CHARM", "CHART", "CHARY", "CHASE",
        "CHASM", "CHEAP", "CHEAT", "CHECK", "CHEEK", "CHEER", "CHEFS", "CHERT", "CHESS", "CHEST",
        "CHEWS", "CHEWY", "CHICK", "CHIDE", "CHIEF", "CHILD", "CHILI", "CHILL", "CHIME", "CHIMP",
        "CHINA", "CHINK", "CHINO", "CHIPS", "CHIRP", "CHIVE", "CHOCK", "CHOIR", "CHOKE", "CHOMP",
        "CHORD", "CHORE", "CHOSE", "CHOWS", "CHUCK", "CHUMP", "CHUNK", "CHURN", "CHUTE", "CIDER",
        "CIGAR", "CINCH", "CIRCA", "CIVIC", "CIVIL", "CLACK", "CLAIM", "CLAMP", "CLAMS", "CLANG",
        "CLANK", "CLANS", "CLAPS", "CLASH", "CLASP", "CLASS", "CLAWS", "CLAYS", "CLEAN", "CLEAR",
        "CLEAT", "CLEFS", "CLEFT", "CLERK", "CLEWS", "CLICK", "CLIFF", "CLIMB", "CLIME", "CLING",
        "CLINK", "CLIPS", "CLOAK", "CLOCK", "CLODS", "CLOGS", "CLONE", "CLONS", "CLOSE", "CLOTH",
        "CLOTS", "CLOUD", "CLOUT", "CLOVE", "CLOWN", "CLUBS", "CLUCK", "CLUES", "CLUMP", "CLUNG",
        "COACH", "COALS", "COAST", "COATS", "COBRA", "COCKS", "COCOA", "CODAS", "CODED", "CODER",
        "CODES", "CODEX", "COEDS", "COILS", "COINS", "COLDS", "COLES", "COLIC", "COLON", "COLOR",
        "COLTS", "COMAS", "COMBO", "COMBS", "COMER", "COMES", "COMET", "COMFY", "COMIC", "COMMA",
        "CONCH", "CONDO", "CONES", "CONGA", "CONIC", "CONKS", "COOED", "COOKS", "COOLS", "COOPS",
        "COPED", "COPES", "COPRA", "COPSE", "CORAL", "CORDS", "CORED", "CORER", "CORES", "CORGI",
        "CORKS", "CORNS", "CORNY", "CORPS", "COSTS", "COTES", "COUCH", "COUGH", "COULD", "COUNT",
        "COUPE", "COUPS", "COURT", "COVEN", "COVER", "COVES", "COVET", "COVEY", "COWED", "COWER",
        "COWLS", "CRABS", "CRACK", "CRAFT", "CRAGS", "CRAMP", "CRAMS", "CRANE", "CRANK", "CRASH",
        "CRASS", "CRATE", "CRAVE", "CRAWL", "CRAWS", "CRAZE", "CRAZY", "CREAK", "CREAM", "CREDO",
        "CREED", "CREEK", "CREEP", "CREME", "CREPE", "CREPT", "CRESS", "CREST", "CREWS", "CRIBS",
        "CRICK", "CRIED", "CRIER", "CRIES", "CRIME", "CRIMP", "CRISP", "CRITS", "CROAK", "CROCK",
        "CROCS", "CROFT", "CRONE", "CRONY", "CROOK", "CROON", "CROPS", "CROSS", "CROUP", "CROWD",
        "CROWN", "CROWS", "CRUDE", "CRUDS", "CRUEL", "CRUET", "CRUMB", "CRUMP", "CRUSH", "CRUST",
        "CRYPT", "CUBED", "CUBES", "CUBIC", "CUBIT", "CUFFS", "CUING", "CULLS", "CULTS", "CUMIN",
        "CUPID", "CURBS", "CURDS", "CURED", "CURER", "CURES", "CURIA", "CURIE", "CURIO", "CURLS",
        "CURLY", "CURRY", "CURSE", "CURVE", "CURVY", "CUSHY", "CUSPS", "CUTIE", "CYBER", "CYCLE",
        "CYNIC", "CYSTS", "CZARS", "DADDY", "DAFFY", "DAILY", "DAIRY", "DAISY", "DALES", "DALLY",
        "DAMES", "DAMNS", "DAMPS", "DANCE", "DANDY", "DARED", "DARES", "DARKS", "DARTS", "DATED",
        "DATER", "DATES", "DATUM", "DAUNT", "DAVIT", "DAWNS", "DAZED", "DAZES", "DEALS", "DEALT",
        "DEANS", "DEARS", "DEATH", "DEBAR", "DEBIT", "DEBTS", "DEBUG", "DEBUT", "DECAF", "DECAL",
        "DECAY", "DECKS", "DECOR", "DECOY", "DECRY", "DEEDS", "DEEMS", "DEEPS", "DEFER", "DEIFY",
        "DEIGN", "DEISM", "DEITY", "DELAY", "DELIS", "DELLS", "DELTA", "DELVE", "DEMON", "DEMOS",
        "DEMUR", "DENIM", "DENSE", "DENTS", "DEPOT", "DEPTH", "DERBY", "DESKS", "DETER", "DETOX",
        "DEUCE", "DEVIL", "DEVON", "DEWAR", "DHOWS", "DIALS", "DIARY", "DICED", "DICES", "DICEY",
        "DICTA", "DIETS", "DIGIT", "DIKED", "DIKES", "DILDO", "DILLS", "DILLY", "DIMER", "DIMES",
        "DIMLY", "DINAR", "DINED", "DINER", "DINES", "DINGO", "DINGS", "DINGY", "DINKY", "DINOS",
        "DIODE", "DIRGE", "DIRTY", "DISCO", "DISCS", "DISKS", "DITCH", "DITTO", "DITTY", "DIVAN",
        "DIVAS", "DIVED", "DIVER", "DIVES", "DIVOT", "DIZZY", "DOCKS", "DODGE", "DODGY", "DODOS",
        "DOERS", "DOFFS", "DOGES", "DOGGY", "DOGMA", "DOILY", "DOING", "DOLED", "DOLES", "DOLLS",
        "DOLLY", "DOLOR", "DOMED", "DOMES", "DONOR", "DONUT", "DOOMS", "DOORS", "DOOZY", "DOPED",
        "DOPES", "DOPEY", "DORMS", "DOSES", "DOTED", "DOTES", "DOTTY", "DOUBT", "DOUGH", "DOURS",
        "DOVES", "DOWDY", "DOWEL", "DOWNS", "DOWNY", "DOWRY", "DOWSE", "DOYEN", "DOZED", "DOZEN",
        "DOZER", "DOZES", "DRABS", "DRAFT", "DRAGS", "DRAIN", "DRAKE", "DRAMA", "DRAMS", "DRANK",
        "DRAPE", "DRAWL", "DRAWN", "DRAWS", "DRAYS", "DREAD", "DREAM", "DREAR", "DRECK", "DREGS",
        "DRESS", "DRIED", "DRIER", "DRIES", "DRIFT", "DRILL", "DRINK", "DRIPS", "DRIVE", "DROIT",
        "DROLL", "DRONE", "DROOL", "DROOP", "DROPS", "DROSS", "DROVE", "DROWN", "DRUBS", "DRUGS",
        "DRUID", "DRUMS", "DRUNK", "DRYAD", "DRYER", "DRYLY", "DUALS", "DUCAT", "DUCHY", "DUCKS",
        "DUCTS", "DUDES", "DUELS", "DUETS", "DUKES", "DULLS", "DULLY", "DULSE", "DUMMY", "DUMPS",
        "DUMPY", "DUNCE", "DUNES", "DUNGS", "DUNKS", "DUPED", "DUPER", "DUPES", "DUPLE", "DURST",
        "DUSKS", "DUSKY", "DUSTS", "DUSTY", "DUTCH", "DUVET", "DWARF", "DWEEB", "DWELL", "DWELT",
        "DYADS", "DYERS", "DYING", "DYKES", "EAGER", "EAGLE", "EARED", "EARLS", "EARLY", "EARNS",
        "EARTH", "EASED", "EASEL", "EASES", "EASTS", "EATEN", "EATER", "EAVES", "EBBED", "EBONY",
        "ECHOS", "EDEMA", "EDGED", "EDGER", "EDGES", "EDICT", "EDIFY", "EDITS", "EERIE", "EGRET",
        "EIDER", "EIGHT", "EJECT", "EKING", "ELAND", "ELATE", "ELBOW", "ELDER", "ELECT", "ELEGY",
        "ELFIC", "ELFIN", "ELIDE", "ELITE", "ELMOS", "ELOPE", "ELUDE", "ELVES", "EMAIL", "EMBED",
        "EMBER", "EMCEE", "EMEND", "EMERY", "EMITS", "EMMET", "EMOJI", "EMOTE", "EMPTY", "ENACT",
        "ENDED", "ENDER", "ENDOW", "ENDUE", "ENEMA", "ENEMY", "ENJOY", "ENNUI", "ENOCH", "ENROL",
        "ENSUE", "ENTER", "ENTRY", "ENVOY", "EOSIN", "EPICS", "EPOCH", "EPOXY", "EQUAL", "EQUIP",
        "ERASE", "ERECT", "ERGOT", "ERICA", "ERODE", "ERRED", "ERROR", "ERUPT", "ESSAY", "ESSEN",
        "ESTER", "ETHER", "ETHIC", "ETHOS", "ETHYL", "EVADE", "EVENS", "EVENT", "EVERY", "EVICT",
        "EVILS", "EVOKE", "EWERS", "EXACT", "EXALT", "EXAMS", "EXCEL", "EXERT", "EXILE", "EXIST",
        "EXITS", "EXPAT", "EXPEL", "EXPOS", "EXTOL", "EXTRA", "EXUDE", "EXULT", "EYING", "EYRIE",
        "FABLE", "FACED", "FACER", "FACES", "FACET", "FACIA", "FACTS", "FADED", "FADER", "FADES",
        "FAILS", "FAINT", "FAIRS", "FAIRY", "FAITH", "FAKED", "FAKER", "FAKES", "FAKIR", "FALLS",
        "FALSE", "FAMED", "FANCY", "FANGS", "FANNY", "FARCE", "FARED", "FARES", "FARMS", "FARTS",
        "FASTS", "FATAL", "FATED", "FATES", "FATSO", "FATTY", "FAULT", "FAUNA", "FAUNS", "FAVES",
        "FAVOR", "FAWNS", "FAXED", "FAXES", "FAZED", "FAZES", "FEARS", "FEAST", "FEATS", "FECAL",
        "FECES", "FEEDS", "FEELS", "FEIGN", "FEINT", "FELLA", "FELLS", "FELON", "FELTS", "FEMME",
        "FEMUR", "FENCE", "FENDS", "FERAL", "FERNS", "FERNY", "FERRY", "FESTS", "FETAL", "FETCH",
        "FETED", "FETES", "FETID", "FETUS", "FEUDS", "FEVER", "FEWER", "FIATS", "FIBER", "FIBRE",
        "FIBRO", "FICHE", "FICHU", "FIEFS", "FIELD", "FIEND", "FIERY", "FIFES", "FIFTH", "FIFTY",
        "FIGHT", "FILCH", "FILED", "FILER", "FILES", "FILET", "FILLS", "FILLY", "FILMS", "FILMY",
        "FILTH", "FINAL", "FINCH", "FINDS", "FINED", "FINER", "FINES", "FINIS", "FINKS", "FINNY",
        "FIORD", "FIRED", "FIRER", "FIRES", "FIRMS", "FIRTH", "FISHY", "FISTS", "FITLY", "FIVER",
        "FIVES", "FIXED", "FIXER", "FIXES", "FIZZY", "FJORD", "FLABS", "FLACK", "FLAGS", "FLAIL",
        "FLAIR", "FLAKE", "FLAKY", "FLAME", "FLANK", "FLANS", "FLAPS", "FLARE", "FLASH", "FLASK",
        "FLATS", "FLAWS", "FLEAS", "FLECK", "FLEES", "FLEET", "FLESH", "FLICK", "FLIER", "FLIES",
        "FLING", "FLINT", "FLIPS", "FLIRT", "FLOAT", "FLOCK", "FLOES", "FLOGS", "FLOOD", "FLOOR",
        "FLOPS", "FLORA", "FLOSS", "FLOUR", "FLOUT", "FLOWN", "FLOWS", "FLUBS", "FLUES", "FLUFF",
        "FLUID", "FLUKE", "FLUKY", "FLUME", "FLUNG", "FLUNK", "FLUSH", "FLUTE", "FLYBY", "FLYER",
        "FOALS", "FOAMS", "FOAMY", "FOCAL", "FOCUS", "FOGEY", "FOGGY", "FOILS", "FOIST", "FOLDS",
        "FOLIA", "FOLIC", "FOLIO", "FOLKS", "FOLLY", "FONDU", "FONTS", "FOODS", "FOOLS", "FOOTS",
        "FORAY", "FORCE", "FORDS", "FORES", "FORGE", "FORGO", "FORKS", "FORMS", "FORTE", "FORTH",
        "FORTS", "FORTY", "FORUM", "FOSSE", "FOULS", "FOUND", "FOUNT", "FOURS", "FOWLS", "FOXED",
        "FOXES", "FOYER", "FRAIL", "FRAME", "FRANC", "FRANK", "FRATS", "FRAUD", "FRAYS", "FREAK",
        "FREED", "FREER", "FREES", "FREON", "FRESH", "FRETS", "FRIAR", "FRIED", "FRIER", "FRIES",
        "FRIGS", "FRILL", "FRISK", "FRITZ", "FROCK", "FROGS", "FROND", "FRONT", "FROSH", "FROST",
        "FROTH", "FROWN", "FROZE", "FRUIT", "FRUMP", "FRYERS", "FUDGE", "FUELS", "FUGAL", "FUGUE",
        "FULLS", "FULLY", "FUMED", "FUMES", "FUNDS", "FUNGI", "FUNKY", "FUNNY", "FURLS", "FUROR",
        "FURRY", "FURZE", "FUSED", "FUSEE", "FUSES", "FUSSY", "FUSTY", "FUTON", "FUZZY", "GABBY",
        "GABLE", "GAFFE", "GAFFS", "GAGER", "GAGES", "GAILY", "GAINS", "GAITS", "GALAS", "GALES",
        "GALLS", "GAMBA", "GAMED", "GAMER", "GAMES", "GAMEY", "GAMIC", "GAMIN", "GAMMA", "GAMUT",
        "GANGS", "GAPED", "GAPER", "GAPES", "GARBS", "GARTH", "GASES", "GASPS", "GASSY", "GATED",
        "GATER", "GATES", "GATOR", "GAUDY", "GAUGE", "GAUNT", "GAUZE", "GAUZY", "GAVEL", "GAVOT",
        "GAWKY", "GAWKS", "GAYER", "GAYLY", "GAZED", "GAZER", "GAZES", "GEARS", "GECKO", "GEEKS",
        "GEEKY", "GEESE", "GELDS", "GELID", "GELTS", "GEMOT", "GENES", "GENIE", "GENII", "GENOA",
        "GENRE", "GENTS", "GENUS", "GEODE", "GERMS", "GERRY", "GETUP", "GHOST", "GHOUL", "GIANT",
        "GIBED", "GIBER", "GIBES", "GIDDY", "GIFTS", "GIGOT", "GILDS", "GILLS", "GILTS", "GIMME",
        "GIMPS", "GIMPY", "GIRDS", "GIRLS", "GIRTH", "GIRTS", "GIVEN", "GIVER", "GIVES", "GIVEY",
        "GLACE", "GLADE", "GLADS", "GLAND", "GLANS", "GLARE", "GLASS", "GLAZE", "GLAZY", "GLEAM",
        "GLEAN", "GLEBE", "GLENS", "GLIDE", "GLINT", "GLITZ", "GLOAM", "GLOAT", "GLOBE", "GLOBS",
        "GLOOM", "GLORY", "GLOSS", "GLOVE", "GLOWS", "GLUED", "GLUER", "GLUES", "GLUEY", "GLUON",
        "GLUTS", "GLYPH", "GNARL", "GNASH", "GNATS", "GNAWS", "GNOME", "GOADS", "GOALS", "GOATS",
        "GODLY", "GOERS", "GOFER", "GOING", "GOLDS", "GOLEM", "GOLFS", "GOLLY", "GONAD", "GONER",
        "GONGS", "GOODS", "GOODY", "GOOEY", "GOOFS", "GOOFY", "GOONS", "GOOSE", "GORAL", "GORED",
        "GORES", "GORGE", "GORPS", "GORSE", "GOUGE", "GOURD", "GOUTY", "GOWNS", "GRABS", "GRACE",
        "GRADE", "GRADS", "GRAFT", "GRAIL", "GRAIN", "GRAMS", "GRAND", "GRANT", "GRAPE", "GRAPH",
        "GRASP", "GRASS", "GRATE", "GRAVE", "GRAVY", "GRAYS", "GRAZE", "GREAT", "GREBE", "GREED",
        "GREEK", "GREEN", "GREET", "GREYS", "GRIDS", "GRIEF", "GRILL", "GRIME", "GRIMY", "GRIND",
        "GRINS", "GRIPE", "GRIPS", "GRIST", "GRITS", "GROAN", "GROAT", "GROIN", "GROOM", "GROPE",
        "GROSS", "GROUP", "GROUT", "GROVE", "GROWL", "GROWN", "GROWS", "GRUBS", "GRUEL", "GRUFF",
        "GRUMP", "GRUNT", "GUANO", "GUARD", "GUAVA", "GUESS", "GUEST", "GUIDE", "GUILD", "GUILE",
        "GUILT", "GUISE", "GULCH", "GULFS", "GULLS", "GULLY", "GULPS", "GUMBO", "GUMMY", "GUNNY",
        "GUPPY", "GURUS", "GUSHY", "GUSTO", "GUSTS", "GUSTY", "GUTSY", "GUTTA", "GUTTY", "GUYED",
        "GYROS", "HABIT", "HACKS", "HADAL", "HADES", "HADJ", "HADST", "HAFIZ", "HAFT", "HAG",
        "HAIKU", "HAILS", "HAIRS", "HAIRY", "HAITI", "HAJJI", "HAKES", "HALER", "HALES", "HALLO",
        "HALLS", "HALOS", "HALTS", "HALVE", "HAMAL", "HAMES", "HAMMY", "HANDS", "HANDY", "HANGS",
        "HANKS", "HANKY", "HAOLE", "HAPLY", "HAPPY", "HARDY", "HAREM", "HARES", "HARKS", "HARMS",
        "HARPS", "HARPY", "HARRY", "HARSH", "HARTS", "HASPS", "HASTE", "HASTY", "HATCH", "HATED",
        "HATER", "HATES", "HAUGH", "HAULS", "HAUNT", "HAUTE", "HAVEN", "HAVER", "HAVES", "HAVOC",
        "HAWKS", "HAWSE", "HAYED", "HAYER", "HAZED", "HAZEL", "HAZER", "HAZES", "HEADS", "HEADY",
        "HEALS", "HEAPS", "HEARD", "HEARS", "HEART", "HEATH", "HEATS", "HEAVE", "HEAVY", "HEDGE",
        "HEEDS", "HEELS", "HEFTS", "HEFTY", "HEIRS", "HEIST", "HELIX", "HELLO", "HELLS", "HELMS",
        "HELPS", "HEMPS", "HEMPY", "HENNA", "HENRY", "HERBS", "HERBY", "HERDS", "HERES", "HERON",
        "HEROS", "HERTZ", "HEWED", "HEWER", "HEXAD", "HEXED", "HEXER", "HEXES", "HICKS", "HIDED",
        "HIDER", "HIDES", "HIGHS", "HIKED", "HIKER", "HIKES", "HILLS", "HILLY", "HILTS", "HINDS",
        "HINGE", "HINTS", "HIPPO", "HIPPY", "HIRED", "HIRER", "HIRES", "HITCH", "HIVED", "HIVES",
        "HOAGY", "HOARD", "HOARS", "HOARY", "HOBBY", "HOBOS", "HOCKS", "HOCUS", "HODGE", "HOE",
        "HOGAN", "HOIST", "HOKEY", "HOLDS", "HOLED", "HOLES", "HOLEY", "HOLLY", "HOLMS", "HOLTS",
        "HOMED", "HOMER", "HOMES", "HOMEY", "HOMOS", "HONED", "HONER", "HONES", "HONEY", "HONKS",
        "HONKY", "HONOR", "HOOCH", "HOODS", "HOODY", "HOOFS", "HOOKS", "HOOKY", "HOOPS", "HOOTS",
        "HOPED", "HOPER", "HOPES", "HORAL", "HORDE", "HORNS", "HORNY", "HORSE", "HORSY", "HOSED",
        "HOSES", "HOSTS", "HOTEL", "HOTLY", "HOUND", "HOURI", "HOURS", "HOUSE", "HOVEL", "HOVER",
        "HOWDY", "HOWLS", "HUBBY", "HUFFS", "HUFFY", "HUGER", "HULAS", "HULKS", "HULLS", "HUMAN",
        "HUMID", "HUMOR", "HUMPS", "HUMUS", "HUNCH", "HUNKS", "HUNKY", "HUNTS", "HURLS", "HURLY",
        "HURRY", "HURTS", "HUSKS", "HUSKY", "HUSSY", "HUTCH", "HYDRA", "HYDRO", "HYENA", "HYMEN",
        "HYMNS", "HYPED", "HYPER", "HYPES", "HYPOS", "IAMBS", "ICHOR", "ICIER", "ICILY", "ICING",
        "ICONS", "IDEAL", "IDEAS", "IDIOM", "IDIOT", "IDLED", "IDLER", "IDLES", "IDOLS", "IDYLL",
        "IGLOO", "ILIAC", "ILIAD", "IMAGE", "IMAGO", "IMAMS", "IMBUE", "IMPEL", "IMPLY", "INANE",
        "INAPT", "INBOX", "INCUR", "INDEX", "INDIA", "INDIE", "INEPT", "INERT", "INFER", "INGOT",
        "INLAY", "INLET", "INNER", "INPUT", "INSET", "INTER", "INTRO", "IONIC", "IOTAS", "IRATE",
        "IRKED", "IRONS", "IRONY", "ISLES", "ISLET", "ISSUE", "ITCHY", "ITEMS", "IVIES", "IVORY",
        "JACKS", "JADED", "JADES", "JAILS", "JAKES", "JAMBS", "JAPAN", "JAPED", "JAPER", "JAPES",
        "JAUNT", "JAWED", "JAZZY", "JEANS", "JEEPS", "JEERS", "JELLY", "JENNY", "JERKS", "JERKY",
        "JESTS", "JESUS", "JETTY", "JEWEL", "JIBED", "JIBES", "JIFFY", "JIHAD", "JILTS", "JINNI",
        "JINNS", "JINX", "JIVED", "JIVES", "JOCKS", "JOEYS", "JOHNS", "JOINS", "JOINT", "JOIST",
        "JOKED", "JOKER", "JOKES", "JOLTS", "JOLTY", "JONAH", "JONES", "JORUM", "JOTTY", "JOULE",
        "JOURS", "JOUST", "JOWLS", "JOWLY", "JOYED", "JUDGE", "JUDOS", "JUICE", "JUICY", "JUJUS",
        "JUKED", "JUKES", "JULEP", "JUMBO", "JUMPS", "JUMPY", "JUNCO", "JUNKS", "JUNKY", "JUNTA",
        "JUNTO", "JUROR", "JUTES", "KABOB", "KAPOK", "KAPPA", "KAPUT", "KARAT", "KARMA", "KART",
        "KAYAK", "KAZOO", "KEBAB", "KEELS", "KEENS", "KEEPS", "KEFIR", "KEPTS", "KERBS", "KERNS",
        "KETCH", "KEYED", "KHAKI", "KHANS", "KICKS", "KICKY", "KIDDO", "KIDDY", "KILNS", "KILOS",
        "KILTS", "KILTY", "KINDA", "KINDS", "KINGS", "KINKS", "KINKY", "KIOSK", "KIRKS", "KITED",
        "KITER", "KITES", "KITTY", "KIWIS", "KLATZ", "KLEEN", "KLIEG", "KLUGE", "KLUTZ", "KNACK",
        "KNAPS", "KNAVE", "KNEAD", "KNEED", "KNEEL", "KNEES", "KNELL", "KNELT", "KNIFE", "KNISH",
        "KNITS", "KNOBS", "KNOCK", "KNOLL", "KNOTS", "KNOWS", "KOALA", "KODAK", "KOLAS", "KOOKS",
        "KOOKY", "KOPJE", "KORAN", "KRAAL", "KRAUT", "KUDOS", "KUDZU", "KYLIX", "LABEL", "LABIA",
        "LABOR", "LACED", "LACER", "LACES", "LACEY", "LACKS", "LADED", "LADEN", "LADER", "LADES",
        "LADLE", "LAGER", "LAIRD", "LAIRS", "LAITY", "LAKES", "LAMAS", "LAMBS", "LAMED", "LAMER",
        "LAMES", "LAMPS", "LANAI", "LANCE", "LANDS", "LANES", "LANKY", "LAPEL", "LAPIN", "LAPSE",
        "LARCH", "LARDS", "LARDY", "LARGE", "LARGO", "LARKS", "LARVA", "LASED", "LASER", "LASES",
        "LASSO", "LASTS", "LATCH", "LATED", "LATEN", "LATER", "LATEX", "LATHE", "LATHS", "LATIN",
        "LATTE", "LAUDS", "LAUGH", "LAVAS", "LAVED", "LAVER", "LAVES", "LAWNS", "LAWNY", "LAXER",
        "LAXLY", "LAYER", "LAYUP", "LAZED", "LAZES", "LEACH", "LEADS", "LEADY", "LEAFS", "LEAFY",
        "LEAKS", "LEAKY", "LEANS", "LEANT", "LEAPS", "LEAPT", "LEARN", "LEASE", "LEASH", "LEAST",
        "LEAVE", "LEDGE", "LEECH", "LEEKS", "LEERS", "LEERY", "LEFTS", "LEFTY", "LEGAL", "LEGGY",
        "LEGIT", "LEMAN", "LEMON", "LEMUR", "LENDS", "LENIS", "LENTO", "LEPER", "LEVEL", "LEVER",
        "LEWIS", "LIARS", "LIBEL", "LIBRA", "LICIT", "LICKS", "LIEGE", "LIENS", "LIFER", "LIFTS",
        "LIGHT", "LIKED", "LIKEN", "LIKER", "LIKES", "LILAC", "LILTS", "LIMBO", "LIMBS", "LIMBY",
        "LIMED", "LIMEN", "LIMES", "LIMEY", "LIMIT", "LIMNS", "LIMOS", "LIMPS", "LINED", "LINEN",
        "LINER", "LINES", "LINGO", "LINKS", "LINUX", "LIONS", "LIPID", "LISPS", "LISTS", "LITHE",
        "LIVED", "LIVEN", "LIVER", "LIVES", "LIVID", "LLAMA", "LOADS", "LOAMY", "LOANS", "LOATH",
        "LOBBY", "LOBED", "LOBES", "LOCAL", "LOCKS", "LOCUS", "LODGE", "LOFTS", "LOFTY", "LOGAN",
        "LOGES", "LOGIC", "LOGIN", "LOGOS", "LOINS", "LOLLS", "LONER", "LONGS", "LOOKS", "LOOMS",
        "LOONS", "LOONY", "LOOPS", "LOOPY", "LOOSE", "LOOTS", "LOPED", "LOPER", "LOPES", "LORDS",
        "LORIS", "LORRY", "LOSER", "LOSES", "LOTTO", "LOTUS", "LOUGH", "LOUTS", "LOVED", "LOVER",
        "LOVES", "LOWED", "LOWER", "LOWLY", "LOXES", "LOYAL", "LUAUS", "LUBED", "LUBES", "LUCID",
        "LUCKS", "LUCKY", "LUCRE", "LULLED", "LULLS", "LUMEN", "LUMPS", "LUMPY", "LUNAR", "LUNCH",
        "LUNES", "LUNGE", "LUNGS", "LUPUS", "LURCH", "LURED", "LURER", "LURES", "LURID", "LURKS",
        "LUSTS", "LUSTY", "LUTES", "LUXES", "LYCRA", "LYING", "LYMPH", "LYNCH", "LYRES", "LYRIC",
        "MACAW", "MACED", "MACES", "MACHO", "MACRO", "MADAM", "MADLY", "MAFIA", "MAGIC", "MAGMA",
        "MAGNA", "MAGOT", "MAGUS", "MAIDS", "MAILS", "MAIMS", "MAINS", "MAIZE", "MAJOR", "MAKER",
        "MAKES", "MALES", "MALLS", "MALTS", "MALTY", "MAMAS", "MAMBO", "MAMMA", "MAMMY", "MANAS",
        "MANED", "MANES", "MANGA", "MANGE", "MANGO", "MANGY", "MANIA", "MANIC", "MANLY", "MANOR",
        "MANSE", "MAPLE", "MAQUI", "MARCH", "MARES", "MARGE", "MARIA", "MARKS", "MARLS", "MARRY",
        "MARSH", "MARTS", "MASER", "MASKS", "MASON", "MASSE", "MASTS", "MATCH", "MATED", "MATER",
        "MATES", "MATEY", "MATHS", "MATIN", "MATTE", "MATTS", "MATZO", "MAULS", "MAUVE", "MAVEN",
        "MAVIS", "MAXIM", "MAXIS", "MAYBE", "MAYOR", "MAYST", "MAZES", "MEALS", "MEALY", "MEANS",
        "MEANT", "MEATS", "MEATY", "MECCA", "MEDAL", "MEDIA", "MEDIC", "MEEDS", "MEETS", "MEGOS",
        "MELBA", "MELDS", "MELON", "MELTS", "MEMOS", "MENDS", "MENUS", "MEOUW", "MEOWS", "MERCY",
        "MERGE", "MERIT", "MERRY", "MESAS", "MESHES", "MESON", "MESSY", "METAL", "METED", "METER",
        "METES", "METRO", "MEWED", "MEZZO", "MIAOU", "MIAOW", "MICAS", "MICKS", "MICRO", "MIDDY",
        "MIDIS", "MIDST", "MIENS", "MIFFS", "MIGHT", "MIKED", "MIKES", "MILCH", "MILER", "MILES",
        "MILKS", "MILKY", "MILLS", "MIMED", "MIMEO", "MIMER", "MIMES", "MIMIC", "MINCE", "MINDS",
        "MINED", "MINER", "MINES", "MINIS", "MINKS", "MINOR", "MINTS", "MINTY", "MINUS", "MIRED",
        "MIRES", "MIRTH", "MISDO", "MISER", "MISSY", "MISTS", "MISTY", "MITER", "MITES", "MITTS",
        "MIXED", "MIXER", "MIXES", "MIZEN", "MOANS", "MOATS", "MOCHA", "MOCKS", "MODAL", "MODEL",
        "MODEM", "MODES", "MOGUL", "MOILS", "MOIRE", "MOIST", "MOLAR", "MOLDS", "MOLDY", "MOLES",
        "MOLLS", "MOLLY", "MOLTS", "MOMMY", "MONAD", "MONEY", "MONKS", "MONTH", "MOOCH", "MOODS",
        "MOODY", "MOOED", "MOONS", "MOONY", "MOORS", "MOOSE", "MOOTS", "MOPED", "MOPER", "MOPES",
        "MOPEY", "MORAL", "MORAY", "MOREL", "MORES", "MORNS", "MORON", "MORPH", "MORTS", "MOSED",
        "MOSES", "MOSSY", "MOSTS", "MOTEL", "MOTES", "MOTET", "MOTHS", "MOTHY", "MOTIF", "MOTOR",
        "MOTTO", "MOUCH", "MOUEE", "MOULD", "MOULT", "MOUND", "MOUNT", "MOURN", "MOUSE", "MOUSY",
        "MOUTH", "MOVED", "MOVER", "MOVES", "MOVIE", "MOWED", "MOWER", "MOXIE", "MUCID", "MUCIN",
        "MUCKS", "MUCKY", "MUCUS", "MUDDY", "MUFFS", "MUFTI", "MUGGY", "MULCH", "MULCT", "MULES",
        "MULEY", "MULLS", "MULTI", "MUMMY", "MUMPS", "MUNCH", "MURAL", "MURKS", "MURKY", "MUSED",
        "MUSER", "MUSES", "MUSHY", "MUSIC", "MUSKS", "MUSKY", "MUSS", "MUSTS", "MUSTY", "MUTED",
        "MUTER", "MUTES", "MUTTS", "MUZZY", "MYNAH", "MYNAS", "MYOPE", "MYRRH", "MYTHS", "NACHO",
        "NADIR", "NAEVE", "NAILS", "NAIVE", "NAKED", "NAMED", "NAMER", "NAMES", "NANAS", "NANCY",
        "NANNY", "NAPES", "NAPPY", "NARCS", "NARDS", "NARES", "NARIS", "NASAL", "NASTY", "NATAL",
        "NATCH", "NATES", "NATTY", "NAVAL", "NAVEL", "NAVES", "NAVVY", "NAZIS", "NEARS", "NEATH",
        "NEATS", "NECKS", "NEEDS", "NEEDY", "NEGRO", "NEIGH", "NEONS", "NERDS", "NERDY", "NERVE",
        "NERVY", "NESTS", "NETTY", "NEVER", "NEWEL", "NEWER", "NEWLY", "NEWSY", "NEWTS", "NEXUS",
        "NICER", "NICHE", "NICKS", "NIECE", "NIFTY", "NIGHT", "NILGA", "NINTH", "NIPPY", "NISEI",
        "NISUS", "NITER", "NITRO", "NITTY", "NIXED", "NIXES", "NOBEL", "NOBLE", "NOBLY", "NODAL",
        "NODDY", "NODES", "NODUS", "NOELS", "NOHOW", "NOISE", "NOISY", "NOMAD", "NONCE", "NONES",
        "NOOKS", "NOONS", "NOOSE", "NORMS", "NORTH", "NOSED", "NOSES", "NOSEY", "NOTCH", "NOTED",
        "NOTER", "NOTES", "NOUNS", "NOVEL", "NUDER", "NUDES", "NUDGE", "NULLS", "NUMBS", "NURSE",
        "NUTTY", "NYLON", "NYMPH", "OAKEN", "OAKUM", "OARSM", "OASES", "OASIS", "OATEN", "OATHS",
        "OBESE", "OBEYS", "OBITS", "OBOES", "OCCUR", "OCEAN", "OCHER", "OCHRE", "OCTAL", "OCTET",
        "ODDER", "ODDLY", "ODIUM", "ODORS", "OFFAL", "OFFED", "OFFER", "OFTEN", "OGEES", "OGLED",
        "OGLER", "OGLES", "OGRES", "OILED", "OILER", "OINKS", "OKAPI", "OKAYS", "OKRAS", "OLDEN",
        "OLDER", "OLDIE", "OLIVE", "OMEGA", "OMENS", "OMITS", "ONION", "ONSET", "ONTOS", "OOMPH",
        "OOZED", "OOZES", "OPALS", "OPENS", "OPERA", "OPINE", "OPIUM", "OPTED", "OPTIC", "ORATE",
        "ORBIT", "ORDER", "ORGAN", "ORIGI", "ORLON", "ORRIS", "OSIER", "OTHER", "OTTER", "OUGHT",
        "OUNCE", "OUSEL", "OUSTS", "OUTDO", "OUTED", "OUTER", "OUTGO", "OVALS", "OVARY", "OVATE",
        "OVENS", "OVERS", "OVERT", "OVINE", "OVOID", "OWING", "OWLET", "OWNED", "OWNER", "OXBOW",
        "OXIDE", "OZONE", "PACED", "PACER", "PACES", "PACKS", "PACTS", "PADDY", "PADRE", "PAEAN",
        "PAGAN", "PAGED", "PAGER", "PAGES", "PAILS", "PAINS", "PAINT", "PAIRS", "PALED", "PALER",
        "PALES", "PALMS", "PALMY", "PALSY", "PANDA", "PANEL", "PANES", "PANGS", "PANIC", "PANSY",
        "PANTS", "PANTY", "PAPAL", "PAPAS", "PAPAW", "PAPER", "PAPPY", "PARCH", "PARED", "PARER",
        "PARES", "PARIS", "PARKA", "PARKS", "PARRY", "PARSE", "PARTS", "PARTY", "PASHA", "PASSE",
        "PASTA", "PASTE", "PASTS", "PASTY", "PATCH", "PATEN", "PATER", "PATES", "PATHS", "PATIO",
        "PAVED", "PAVER", "PAVES", "PAWED", "PAWLS", "PAWNS", "PAYED", "PAYEE", "PAYER", "PEACE",
        "PEACH", "PEAKS", "PEAKY", "PEALS", "PEARL", "PEARS", "PEART", "PEASE", "PEATY", "PECAN",
        "PECKS", "PEDAL", "PEEKS", "PEELS", "PEEPS", "PEERS", "PEEVE", "PEWIT", "PELTS", "PENAL",
        "PENCE", "PENIS", "PENNY", "PEONS", "PEONY", "PERCH", "PERDU", "PERIL", "PERKS", "PERKY",
        "PESKY", "PESOS", "PESTS", "PETAL", "PETAR", "PETER", "PETIT", "PETTY", "PEWEE", "PHAGE",
        "PHASE", "PHIAL", "PHLOX", "PHONE", "PHONY", "PHOTO", "PHYLA", "PIANO", "PICCO", "PICKS",
        "PICKY", "PICOT", "PIECE", "PIERS", "PIETY", "PIGGY", "PIKER", "PIKES", "PILAF", "PILED",
        "PILES", "PILLS", "PILOT", "PIMPS", "PINCH", "PINED", "PINES", "PINEY", "PINGS", "PINKO",
        "PINKS", "PINTO", "PINTS", "PINUP", "PIONS", "PIOUS", "PIPED", "PIPER", "PIPES", "PIPIT",
        "PIQUE", "PISCO", "PITCH", "PITHY", "PITON", "PIVOT", "PIXEL", "PIXIE", "PIZZA", "PLACE",
        "PLACK", "PLAID", "PLAIN", "PLAIT", "PLANE", "PLANK", "PLANS", "PLANT", "PLASH", "PLASM",
        "PLATE", "PLATS", "PLAYA", "PLAYS", "PLAZA", "PLEAD", "PLEAS", "PLEAT", "PLEBE", "PLEBS",
        "PLENA", "PLIED", "PLIER", "PLIES", "PLINK", "PLODS", "PLOPS", "PLOTS", "PLOYS", "PLUCK",
        "PLUGS", "PLUMB", "PLUME", "PLUMP", "PLUMS", "PLUMY", "PLUNK", "PLUSH", "PLYER", "POACH",
        "POCKS", "POCKY", "PODIA", "POEMS", "POESY", "POETS", "POINT", "POISE", "POKED", "POKER",
        "POKES", "POKEY", "POLAR", "POLED", "POLER", "POLES", "POLIO", "POLKA", "POLLS", "POLYP",
        "POMPS", "PONDS", "PONES", "POOCH", "POOHS", "POOLS", "POOPS", "POPES", "POPPY", "PORCH",
        "PORED", "PORES", "PORGY", "PORKS", "PORKY", "PORNO", "PORTS", "POSED", "POSER", "POSES",
        "POSIT", "POSSE", "POSTS", "POTTY", "POUCH", "POUFS", "POUND", "POURS", "POUTS", "POUTY",
        "POWER", "POXES", "PRAMS", "PRANK", "PRAOS", "PRASE", "PRATE", "PRAWN", "PRAYS", "PREEN",
        "PREPS", "PRESS", "PREXY", "PREYS", "PRICE", "PRICK", "PRIDE", "PRIED", "PRIER", "PRIES",
        "PRIGS", "PRIMA", "PRIME", "PRIMO", "PRIMP", "PRIMS", "PRINK", "PRINT", "PRIOR", "PRISM",
        "PRIVY", "PRIZE", "PROBE", "PRODS", "PROEM", "PROFS", "PROMO", "PROMS", "PRONE", "PRONG",
        "PROOF", "PROPS", "PROSE", "PROSY", "PROUD", "PROVE", "PROWL", "PROWS", "PROXY", "PRUDE",
        "PRUNE", "PRUTA", "PSALM", "PSEUD", "PSHAW", "PSYCH", "PUBIC", "PUBIS", "PUCKS", "PUDGY",
        "PUFFS", "PUFFY", "PUKED", "PUKES", "PULLS", "PULPS", "PULPY", "PULSE", "PUMAS", "PUMPS",
        "PUNCH", "PUNKS", "PUNKY", "PUNNY", "PUNTS", "PUPAE", "PUPAL", "PUPAS", "PUPIL", "PUPPY",
        "PUREE", "PURER", "PURGE", "PURLS", "PURRS", "PURSE", "PURSY", "PUSHY", "PUSSY", "PUTTS",
        "PUTTY", "PYGMY", "PYLON", "PYRES", "PYXES", "QUACK", "QUADS", "QUAFF", "QUAGS", "QUAIL",
        "QUAKE", "QUAKY", "QUALM", "QUANT", "QUARK", "QUART", "QUASH", "QUASI", "QUAYS", "QUEEN",
        "QUEER", "QUELL", "QUERN", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIDS", "QUIET", "QUIFF",
        "QUILL", "QUILT", "QUINT", "QUIPS", "QUIPU", "QUIRE", "QUIRK", "QUIRT", "QUITE", "QUITS",
        "QUODS", "QUOIN", "QUOIT", "QUOTA", "QUOTE", "QUOTH", "RABBI", "RABID", "RACED", "RACER",
        "RACES", "RACKS", "RADAR", "RADII", "RADIO", "RADIX", "RADON", "RAFTS", "RAGAS", "RAGED",
        "RAGES", "RAGGY", "RAIDS", "RAILS", "RAINS", "RAINY", "RAISE", "RAJAH", "RAJAS", "RAKED",
        "RAKER", "RAKES", "RALLY", "RAMPS", "RANCH", "RANDS", "RANDY", "RANGE", "RANGY", "RANKS",
        "RANTS", "RAPED", "RAPER", "RAPES", "RAPID", "RARER", "RARES", "RASPS", "RASPY", "RATED",
        "RATER", "RATES", "RATIO", "RATTY", "RAVED", "RAVEL", "RAVEN", "RAVER", "RAVES", "RAWER",
        "RAYED", "RAYON", "RAZED", "RAZER", "RAZES", "RAZOR", "REACH", "REACT", "READS", "READY",
        "REALM", "REALS", "REAMS", "REAPS", "REARS", "REBEL", "REBID", "REBUS", "REBUT", "RECAP",
        "RECCO", "RECON", "RECTO", "RECUT", "REDID", "REDIP", "REDLY", "REDOX", "REDUX", "REEDS",
        "REEDY", "REEFS", "REEKS", "REEKY", "REELS", "REEVE", "REFER", "REFIT", "REGAL", "REHAB",
        "REIFY", "REIGN", "REINS", "RELAX", "RELAY", "RELIC", "REMAN", "REMAP", "REMIT", "REMIX",
        "RENAL", "RENDS", "RENEW", "RENTS", "REPAY", "REPEL", "REPIN", "REPLY", "RESET", "RESIN",
        "RESOW", "RESTS", "RETCH", "RETRO", "RETRY", "REUSE", "REVEL", "REVET", "REVUE", "RHEAS",
        "RHEUM", "RHINO", "RHUMB", "RHYME", "RIALS", "RIBBY", "RICED", "RICER", "RICES", "RICKS",
        "RIDER", "RIDES", "RIDGE", "RIDGY", "RIFLE", "RIFTS", "RIGHT", "RIGID", "RIGOR", "RILED",
        "RILES", "RILLS", "RIMED", "RIMES", "RINGS", "RINKS", "RINSE", "RIOTS", "RIPEN", "RIPER",
        "RIPES", "RISEN", "RISER", "RISES", "RISKS", "RISKY", "RITES", "RITZY", "RIVAL", "RIVED",
        "RIVEN", "RIVER", "RIVES", "RIVET", "ROACH", "ROADS", "ROAMS", "ROANS", "ROARS", "ROAST",
        "ROBED", "ROBES", "ROBIN", "ROBOT", "ROCKS", "ROCKY", "RODEO", "ROGER", "ROGUE", "ROILS",
        "ROLES", "ROLLS", "ROMAN", "ROMPS", "RONDO", "ROODS", "ROOFS", "ROOKS", "ROOKY", "ROOMS",
        "ROOMY", "ROOST", "ROOTS", "ROOTY", "ROPED", "ROPER", "ROPES", "ROSES", "ROSHI", "ROSIN",
        "ROTAS", "ROTOR", "ROUGE", "ROUGH", "ROUND", "ROUSE", "ROUST", "ROUTE", "ROUTS", "ROVED",
        "ROVER", "ROVES", "ROWAN", "ROWDY", "ROWED", "ROWER", "ROYAL", "RUBES", "RUBLE", "RUCHE",
        "RUDDY", "RUDER", "RUFFS", "RUGBY", "RUINS", "RULED", "RULER", "RULES", "RUMBA", "RUMEN",
        "RUMMY", "RUMOR", "RUMPS", "RUNES", "RUNGS", "RUNIC", "RUNNY", "RUNTS", "RUNTY", "RUPEE",
        "RURAL", "RUSES", "RUSKS", "RUSTS", "RUSTY", "RUTHS", "RUTTY", "SABER", "SABLE", "SABOT",
        "SABRA", "SABRE", "SACKS", "SACRA", "SADLY", "SAFER", "SAFES", "SAGAS", "SAGER", "SAGES",
        "SAHIB", "SAILS", "SAINT", "SAITH", "SALAD", "SALEP", "SALES", "SALIC", "SALLY", "SALON",
        "SALSA", "SALTS", "SALTY", "SALVE", "SALVO", "SAMBA", "SAMBO", "SAMEK", "SANER", "SAPID",
        "SAPOR", "SAPPY", "SARAN", "SARGE", "SARIS", "SAROD", "SASSY", "SATAN", "SATED", "SATES",
        "SATIN", "SATYR", "SAUCE", "SAUCY", "SAUNA", "SAUTE", "SAVED", "SAVER", "SAVES", "SAVOR",
        "SAVVY", "SAWED", "SAWER", "SAXES", "SAYER", "SCABS", "SCADS", "SCALD", "SCALE", "SCALP",
        "SCALY", "SCAMP", "SCAMS", "SCANS", "SCANT", "SCARE", "SCARF", "SCARP", "SCARS", "SCARY",
        "SCATS", "SCENE", "SCENT", "SCHMO", "SCHWA", "SCION", "SCOFF", "SCOLD", "SCONE", "SCOOP",
        "SCOOT", "SCOPE", "SCOPS", "SCORE", "SCORN", "SCOTS", "SCOUR", "SCOUT", "SCOWL", "SCOWS",
        "SCRAM", "SCRAP", "SCREW", "SCRIP", "SCROD", "SCRUB", "SCUBA", "SCUDS", "SCUFF", "SCULL",
        "SCUMS", "SCURF", "SEALS", "SEAMS", "SEAMY", "SEARS", "SEATS", "SEBUM", "SECCO", "SECTS",
        "SEDAN", "SEDER", "SEDGE", "SEDGY", "SEDUM", "SEEDS", "SEEDY", "SEEKS", "SEEMS", "SEEPS",
        "SEEPY", "SEERS", "SEGNO", "SEGUE", "SEINE", "SEIZE", "SELAH", "SELFS", "SELLS", "SEMEN",
        "SEMIS", "SENDS", "SENNA", "SENOR", "SENSE", "SEPAL", "SEPIA", "SEPOY", "SEPTA", "SEPTS",
        "SERAI", "SERFS", "SERGE", "SERIF", "SERIN", "SERUM", "SERVE", "SERVO", "SETUP", "SEVEN",
        "SEVER", "SEWED", "SEWER", "SEXED", "SEXES", "SHACK", "SHADE", "SHADY", "SHAFT", "SHAGS",
        "SHAHI", "SHAHS", "SHAKE", "SHAKY", "SHALE", "SHALL", "SHALT", "SHAME", "SHAMS", "SHANK",
        "SHAPE", "SHARD", "SHARE", "SHARK", "SHARP", "SHAVE", "SHAWL", "SHAWM", "SHEAF", "SHEAR",
        "SHEDS", "SHEEN", "SHEEP", "SHEER", "SHEET", "SHEIK", "SHELF", "SHELL", "SHEP", "SHIED",
        "SHIER", "SHIES", "SHIFT", "SHILL", "SHINE", "SHINS", "SHINY", "SHIPS", "SHIRE", "SHIRK",
        "SHIRR", "SHIRT", "SHIST", "SHITS", "SHIVA", "SHIVE", "SHOAL", "SHOCK", "SHOED", "SHOES",
        "SHONE", "SHOOK", "SHOON", "SHOOS", "SHOOT", "SHOPS", "SHORE", "SHORN", "SHORT", "SHOTS",
        "SHOUT", "SHOVE", "SHOWN", "SHOWS", "SHOWY", "SHRED", "SHREW", "SHRUB", "SHRUG", "SHUCK",
        "SHUNS", "SHUNT", "SHUSH", "SHUTS", "SHYLY", "SIBYL", "SICKO", "SICKS", "SIDED", "SIDES",
        "SIEGE", "SIENA", "SIEVE", "SIFTS", "SIGHS", "SIGHT", "SIGMA", "SIGNS", "SILKS", "SILKY",
        "SILLS", "SILLY", "SILOS", "SILTS", "SILTY", "SILVA", "SIMAR", "SINCE", "SINES", "SINEW",
        "SINGE", "SINGS", "SINKS", "SINUS", "SIRED", "SIREE", "SIREN", "SIRES", "SIRUP", "SISAL",
        "SISSY", "SITAR", "SITED", "SITES", "SIXES", "SIXTH", "SIXTY", "SIZED", "SIZER", "SIZES",
        "SKATE", "SKEET", "SKEIN", "SKEWS", "SKIDS", "SKIED", "SKIER", "SKIES", "SKIFF", "SKILL",
        "SKIMP", "SKIMS", "SKINS", "SKINT", "SKIPS", "SKIRT", "SKITS", "SKULK", "SKULL", "SKUNK",
        "SLABS", "SLACK", "SLAGS", "SLAIN", "SLAKE", "SLAMS", "SLANG", "SLANT", "SLAPS", "SLASH",
        "SLATE", "SLATS", "SLAVS", "SLAWS", "SLAYS", "SLEDS", "SLEEK", "SLEEP", "SLEET", "SLEPT",
        "SLICE", "SLICK", "SLIDE", "SLIER", "SLILY", "SLIME", "SLIMS", "SLIMY", "SLING", "SLINK",
        "SLIPS", "SLITS", "SLOES", "SLOGS", "SLOOP", "SLOPE", "SLOPS", "SLOSH", "SLOTH", "SLOTS",
        "SLOWS", "SLUED", "SLUES", "SLUGS", "SLUMP", "SLUMS", "SLUNG", "SLUNK", "SLURP", "SLURS",
        "SLUSH", "SLUTS", "SLYER", "SLYLY", "SMACK", "SMALL", "SMART", "SMASH", "SMEAR", "SMELL",
        "SMELT", "SMILE", "SMIRK", "SMITE", "SMITH", "SMOCK", "SMOKE", "SMOKY", "SMOTE", "SMUTS",
        "SNACK", "SNAFU", "SNAGS", "SNAIL", "SNAKE", "SNAKY", "SNAPS", "SNARE", "SNARL", "SNEAK",
        "SNEER", "SNELL", "SNICK", "SNIDE", "SNIFF", "SNIPE", "SNIPS", "SNOBS", "SNOOD", "SNOOP",
        "SNOOT", "SNORE", "SNORT", "SNOTS", "SNOUT", "SNOWS", "SNOWY", "SNUBS", "SNUFF", "SNUGS",
        "SOAKS", "SOAPS", "SOAPY", "SOARS", "SOBER", "SOCLE", "SOCKS", "SODA", "SODAS", "SODDY",
        "SODOM", "SOFAS", "SOFTS", "SOFTY", "SOGGY", "SOILS", "SOLAR", "SOLED", "SOLES", "SOLID",
        "SOLOS", "SOLUM", "SOLVE", "SONAR", "SONGS", "SONIC", "SONNY", "SOOTH", "SOOTS", "SOOTY",
        "SOPOR", "SOPPY", "SORER", "SORES", "SORRY", "SORTS", "SOUCH", "SOUGH", "SOULS", "SOUND",
        "SOUPS", "SOUPY", "SOURS", "SOUSE", "SOUTH", "SOWED", "SOWER", "SPACE", "SPACY", "SPADE",
        "SPAKE", "SPAMS", "SPANK", "SPANS", "SPARE", "SPARK", "SPARS", "SPASM", "SPATE", "SPATS",
        "SPAWN", "SPAYS", "SPEAK", "SPEAR", "SPECK", "SPECS", "SPEED", "SPELL", "SPELT", "SPEND",
        "SPENT", "SPERM", "SPEWS", "SPICA", "SPICE", "SPICY", "SPIED", "SPIEL", "SPIER", "SPIES",
        "SPIKE", "SPIKY", "SPILL", "SPILT", "SPINE", "SPINS", "SPINY", "SPIRE", "SPIRY", "SPITE",
        "SPITS", "SPITZ", "SPLAT", "SPLAY", "SPLIT", "SPOIL", "SPOKE", "SPOOF", "SPOOK", "SPOOL",
        "SPOON", "SPOOR", "SPORE", "SPORT", "SPOTS", "SPOUT", "SPRAE", "SPRAT", "SPRAY", "SPREE",
        "SPRIG", "SPUDS", "SPUME", "SPUMY", "SPUNK", "SPURS", "SPURT", "SPUTA", "SQUAB", "SQUAD",
        "SQUAT", "SQUAW", "SQUIB", "SQUID", "STABS", "STACK", "STAFF", "STAGE", "STAGS", "STAGY",
        "STAID", "STAIN", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND", "STANE",
        "STANK", "STAPH", "STARE", "STARK", "STARS", "START", "STASH", "STATE", "STATS", "STAVE",
        "STAYS", "STEAD", "STEAK", "STEAL", "STEAM", "STEED", "STEEL", "STEEP", "STEER", "STEMS",
        "STENO", "STEPS", "STERN", "STETS", "STEWS", "STICK", "STIFF", "STILE", "STILL", "STILT",
        "STING", "STINK", "STINT", "STIRS", "STOAS", "STOAT", "STOCK", "STOIC", "STOKE", "STOLE",
        "STOMA", "STOMP", "STONE", "STONI", "STONY", "STOOD", "STOOL", "STOOP", "STOPS", "STORE",
        "STORK", "STORM", "STORY", "STOUT", "STOVE", "STRAP", "STRAW", "STRAY", "STREP", "STREW",
        "STRIA", "STRIP", "STROP", "STRUM", "STRUT", "STUBS", "STUCK", "STUDS", "STUDY", "STUFF",
        "STUMP", "STUNG", "STUNK", "STUNS", "STUNT", "STYLE", "STYLI", "SUAVE", "SUCKS", "SUCRE",
        "SUDAN", "SUDDS", "SUDOR", "SUEDS", "SUEDE", "SUETS", "SUETY", "SUGAR", "SUING", "SUITE",
        "SUITS", "SULFA", "SULKS", "SULKY", "SULLY", "SUMAC", "SUMMA", "SUMPS", "SUNNY", "SUNUP",
        "SUPER", "SUPES", "SUPRA", "SURAH", "SURDS", "SURER", "SURFS", "SURFY", "SURGE", "SURLY",
        "SUSHI", "SUTRA", "SWABS", "SWAGE", "SWAGS", "SWAIN", "SWAMI", "SWAMP", "SWANK", "SWANS",
        "SWAPS", "SWARD", "SWARF", "SWARM", "SWART", "SWASH", "SWATH", "SWATS", "SWAYS", "SWEAR",
        "SWEAT", "SWEDE", "SWEEP", "SWEET", "SWELL", "SWEPT", "SWIFT", "SWIGS", "SWILL", "SWIMS",
        "SWINE", "SWING", "SWINK", "SWIPE", "SWIRL", "SWISH", "SWISS", "SWIVE", "SWOON", "SWOOP",
        "SWORD", "SWORE", "SWORN", "SWUNG", "SYLPH", "SYNOD", "SYRUP", "TABBY", "TABES", "TABLE",
        "TABOO", "TABOR", "TACIT", "TACKS", "TACKY", "TACOS", "TACTS", "TAFFY", "TAILS", "TAINT",
        "TAKEN", "TAKER", "TAKES", "TALCS", "TALES", "TALKS", "TALKY", "TALLY", "TALON", "TALUS",
        "TAMED", "TAMER", "TAMES", "TAMMY", "TAMPS", "TANGO", "TANGS", "TANGY", "TANKS", "TANSY",
        "TAPED", "TAPER", "TAPES", "TAPIR", "TAPIS", "TARDI", "TARDY", "TARES", "TARNS", "TAROS",
        "TAROT", "TARPS", "TARRY", "TARTS", "TARTY", "TASKS", "TASTE", "TASTY", "TATER", "TATTY",
        "TAUNT", "TAWNY", "TAXED", "TAXER", "TAXES", "TAXIS", "TEACH", "TEAKS", "TEALS", "TEAMS",
        "TEARS", "TEARY", "TEASE", "TEATS", "TECHS", "TEDDY", "TEEMS", "TEENS", "TEENY", "TEETH",
        "TELEX", "TELLS", "TELLY", "TEMPI", "TEMPO", "TEMPS", "TEMPT", "TENCH", "TENDS", "TENET",
        "TENON", "TENOR", "TENSE", "TENTH", "TENTS", "TEPEE", "TEPID", "TERCE", "TERMS", "TERNS",
        "TERRA", "TERRY", "TERSE", "TESTS", "TESTY", "TETRA", "TEXAS", "TEXTS", "THANE", "THANK",
        "THAWS", "THEFT", "THEGN", "THEIR", "THEME", "THENS", "THERE", "THERM", "THESE", "THETA",
        "THICK", "THIEF", "THIGH", "THINE", "THING", "THINK", "THINS", "THIRD", "THIRL", "THOLE",
        "THONG", "THORN", "THORO", "THORP", "THOSE", "THOUS", "THREE", "THREW", "THRIP", "THROB",
        "THROE", "THROW", "THRUM", "THUDS", "THUGS", "THUMB", "THUMP", "THUNK", "THURL", "THYME",
        "TIARA", "TIBIA", "TICKS", "TIDAL", "TIDED", "TIDES", "TIERS", "TIFFS", "TIGER", "TIGHT",
        "TIKES", "TILDE", "TILED", "TILER", "TILES", "TILLS", "TILTH", "TILTS", "TIMED", "TIMER",
        "TIMES", "TIMID", "TINDS", "TINGE", "TINGS", "TINNY", "TINTS", "TIPIS", "TIPPY", "TIPSY",
        "TIRED", "TIRES", "TITAN", "TITHE", "TITLE", "TITTY", "TIVIS", "TIZZY", "TOADS", "TOADY",
        "TOAST", "TODAY", "TODDY", "TOFFS", "TOFFY", "TOGAS", "TOILS", "TOKES", "TOKEN", "TOLLS",
        "TOMBS", "TOMES", "TONAL", "TONED", "TONER", "TONES", "TONGS", "TONIC", "TONNE", "TOOLS",
        "TOOTH", "TOOTS", "TOPAZ", "TOPIC", "TOQUE", "TORCH", "TORIC", "TOROS", "TORSO", "TORTE",
        "TORTS", "TORUS", "TOTAL", "TOTED", "TOTER", "TOTES", "TOTEM", "TOUCH", "TOUGH", "TOURS",
        "TOUTS", "TOWED", "TOWEL", "TOWER", "TOWNS", "TOWNY", "TOXIC", "TOXIN", "TOYED", "TOYER",
        "TRACE", "TRACK", "TRACT", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TRAMP", "TRAMS", "TRAPS",
        "TRASH", "TRAVE", "TRAWL", "TRAYS", "TREAD", "TREAT", "TREED", "TREES", "TREKS", "TREND",
        "TRESS", "TRIAD", "TRIAL", "TRIBE", "TRICE", "TRICK", "TRIED", "TRIER", "TRIES", "TRIKE",
        "TRILL", "TRIMS", "TRINE", "TRIOS", "TRIPE", "TRIPS", "TRITE", "TROLL", "TROMP", "TROOP",
        "TROPE", "TROTH", "TROTS", "TROUT", "TROVE", "TRUCE", "TRUCK", "TRUED", "TRUER", "TRUES",
        "TRULY", "TRUMP", "TRUNK", "TRUSS", "TRUST", "TRUTH", "TRYST", "TSARS", "TUBAL", "TUBAS",
        "TUBBY", "TUBED", "TUBER", "TUBES", "TUCKS", "TUFAS", "TUFTS", "TUFTY", "TULIP", "TULLE",
        "TUMID", "TUMMY", "TUMOR", "TUNAS", "TUNED", "TUNER", "TUNES", "TUNIC", "TUNNY", "TURBO",
        "TURDS", "TURFS", "TURFY", "TURNS", "TURPS", "TUSKS", "TUTOR", "TUTUS", "TUXES", "TWAIN",
        "TWANG", "TWEAK", "TWEED", "TWEEN", "TWEET", "TWICE", "TWIGS", "TWILL", "TWINE", "TWINS",
        "TWIRL", "TWIST", "TWITS", "TWIXT", "TYING", "TYKES", "TYPED", "TYPES", "TYPIC", "TYPOS",
        "TYROS", "TZARS", "UDDER", "UHLAN", "ULCER", "ULNAE", "ULNAR", "ULNAS", "ULTRA", "UMBEL",
        "UMBER", "UMBRA", "UNAPT", "UNARM", "UNARY", "UNBID", "UNCAP", "UNCLE", "UNCO", "UNCUT",
        "UNDER", "UNDID", "UNDUE", "UNFED", "UNFIT", "UNFIX", "UNGET", "UNHAT", "UNIFY", "UNION",
        "UNITE", "UNITS", "UNITY", "UNLIT", "UNMAN", "UNMET", "UNMUD", "UNPIN", "UNRIG", "UNSAY",
        "UNSET", "UNSEW", "UNTIE", "UNTIL", "UNWED", "UNWON", "UNZIP", "UPBEAT", "UPBOW", "UPDRY",
        "UPEND", "UPPED", "UPPER", "UPSET", "URBAN", "UREAS", "URGED", "URGER", "URGES", "URINE",
        "USAGE", "USERS", "USHER", "USING", "USUAL", "USURP", "USURY", "UTERI", "UTILE", "UTTER",
        "UVULA", "VACUA", "VAGUE", "VAGUS", "VALES", "VALET", "VALID", "VALOR", "VALSE", "VALUE",
        "VALVE", "VAMPS", "VANES", "VAPID", "VAPOR", "VASES", "VASTS", "VAULT", "VAUNT", "VEALS",
        "VEEPS", "VEERS", "VEGAN", "VEILS", "VEINS", "VEINY", "VELAR", "VELDS", "VELDT", "VENAL",
        "VENDS", "VENOM", "VENTI", "VENTS", "VENUE", "VERBS", "VERGE", "VERSA", "VERSE", "VERSO",
        "VERST", "VERVE", "VESTS", "VETCH", "VEXED", "VEXER", "VEXES", "VIALS", "VIAND", "VIBES",
        "VICAR", "VICES", "VIDEO", "VIEWS", "VIGIL", "VIGOR", "VILLI", "VINES", "VINYL", "VIOLA",
        "VIOLS", "VIPER", "VIRAL", "VIREO", "VIRUS", "VISAS", "VISED", "VISES", "VISIT", "VISOR",
        "VISTA", "VITAE", "VITAL", "VIVAS", "VIVID", "VIXEN", "VIZOR", "VOCAL", "VODKA", "VOGUE",
        "VOICE", "VOIDS", "VOILE", "VOLES", "VOLTS", "VOMIT", "VOTED", "VOTER", "VOTES", "VOUCH",
        "VOWED", "VOWEL", "VOWER", "VROOM", "VULVA", "VYING", "WACKO", "WACKS", "WACKY", "WADED",
        "WADER", "WADES", "WADIS", "WAFER", "WAFTS", "WAGED", "WAGER", "WAGES", "WAGON", "WAIFS",
        "WAILS", "WAIST", "WAITS", "WAIVE", "WAKED", "WAKEN", "WAKER", "WAKES", "WALED", "WALES",
        "WALKS", "WALLS", "WALTZ", "WANDS", "WANED", "WANES", "WANLY", "WANTS", "WARDS", "WARES",
        "WARMS", "WARNS", "WARPS", "WARTS", "WARTY", "WASHY", "WASPS", "WASPY", "WASTE", "WATCH",
        "WATER", "WATTS", "WAVED", "WAVER", "WAVES", "WAVEY", "WAXED", "WAXEN", "WAXER", "WAXES",
        "WEALD", "WEALS", "WEANS", "WEARS", "WEARY", "WEAVE", "WEBBY", "WEDGE", "WEDGY", "WEEDS",
        "WEEDY", "WEEKS", "WEENY", "WEEPS", "WEEPY", "WEFTS", "WEIGH", "WEIRD", "WEIRS", "WELCH",
        "WELDS", "WELLS", "WELSH", "WELTS", "WENCH", "WENDS", "WETLY", "WHACK", "WHALE", "WHARF",
        "WHATS", "WHEAT", "WHEEL", "WHELK", "WHELM", "WHELP", "WHENS", "WHERE", "WHETS", "WHICH",
        "WHIFF", "WHILE", "WHIMS", "WHINE", "WHINY", "WHIPS", "WHIRL", "WHIRR", "WHIRS", "WHISH",
        "WHISK", "WHIST", "WHITE", "WHITS", "WHIZZ", "WHOLE", "WHOMP", "WHOOP", "WHOPS", "WHORE",
        "WHORL", "WHOSE", "WICKS", "WIDEN", "WIDER", "WIDOW", "WIDTH", "WIELD", "WIFEY", "WILDS",
        "WILES", "WILLS", "WILLY", "WILTS", "WINCE", "WINCH", "WINDS", "WINDY", "WINED", "WINES",
        "WINEY", "WINGS", "WINGY", "WINKS", "WINOS", "WIPED", "WIPER", "WIPES", "WIRED", "WIRER",
        "WIRES", "WISED", "WISER", "WISES", "WISPS", "WISPY", "WITCH", "WITHS", "WITHY", "WITTY",
        "WIVED", "WIVES", "WIZEN", "WIZES", "WOADS", "WOKEN", "WOLDS", "WOMAN", "WOMBS", "WOMEN",
        "WONKY", "WONTS", "WOODS", "WOODY", "WOOED", "WOOER", "WOOFS", "WOOLS", "WOOLY", "WOOZY",
        "WORDS", "WORDY", "WORKS", "WORLD", "WORMS", "WORMY", "WORRY", "WORSE", "WORST", "WORTH",
        "WOULD", "WOUND", "WOVEN", "WOWED", "WRACK", "WRAPS", "WRAPT", "WRATH", "WREAK", "WRECK",
        "WRENS", "WREST", "WRIER", "WRING", "WRIST", "WRITE", "WRITS", "WRONG", "WROTE", "WROTH",
        "WRUNG", "WRYLY", "XENON", "XEROX", "XYLEM", "YACHT", "YARDS", "YARNS", "YAWED", "YAWLS",
        "YAWNS", "YEAHS", "YEARN", "YEARS", "YEAST", "YELLS", "YELPS", "YETIS", "YIELD", "YODEL",
        "YOKED", "YOKEL", "YOKES", "YOLKS", "YOLKY", "YONIS", "YOUTH", "YUCCA", "YUMMY", "ZAPPY",
        "ZEALS", "ZEBRA", "ZEBUS", "ZEROS", "ZESTS", "ZESTY", "ZILCH", "ZINCS", "ZINGS", "ZIPPY",
        "ZONAL", "ZONED", "ZONES", "ZOOMS"
    ];

    SUPPLEMENTARY_GUESSES.forEach(function(w) {
        if (w.length === 5) VALID_WORDS_SET[w] = true;
    });

    // Game Session State
    var sessionId = null;
    var isMultiplayer = false;
    var myPlayerName = "Coder";
    var myPlayerNumber = 1;
    var isGameOver = false;
    var hardMode = false;
    var gameStartTime = Date.now();

    var targetWord = "CODED";
    var maxAttempts = 6;
    var wordLength = 5;
    var currentRow = 0;
    var currentCol = 0;
    var currentGuess = [];
    var boardGuesses = []; // Stores { word: "CRANE", result: ["G", "Y", "A", "G", "A"] }

    // Known hints for Hard Mode validation
    var revealedGreenHints = {}; // index -> letter
    var revealedYellowHints = {}; // letter -> true
    var keyboardKeyStates = {}; // letter -> 'correct' | 'present' | 'absent'

    var WordDuel = {
        init: function() {
            var urlParams = new URLSearchParams(window.location.search);
            sessionId = urlParams.get('session');
            var modeParam = urlParams.get('mode') || 'standard';
            var seedParam = parseInt(urlParams.get('seed'), 10);
            var p1Url = urlParams.get('p1') || '';
            var p2Url = urlParams.get('p2') || '';

            if (modeParam === 'hard') {
                hardMode = true;
                $('#hard-mode-toggle').prop('checked', true);
            }

            if (sessionId) {
                isMultiplayer = true;
                $('#multiplayer-telemetry-card').show();
                this.initMultiplayer(p1Url, p2Url, seedParam);
            } else {
                $('#multiplayer-telemetry-card').hide();
                this.pickSecretWord(seedParam);
            }

            this.buildBoard();
            this.buildKeyboard();
            this.bindEvents();
            this.updateStatsDisplay();
        },

        initMultiplayer: function(p1Url, p2Url, seed) {
            var self = this;
            if (window.GameHubClient && window.GameHubClient.isConnected()) {
                var player = window.GameHubClient.getCurrentPlayer();
                if (player) {
                    myPlayerName = player.DisplayName;
                    if (p1Url && stringEquals(p1Url, myPlayerName)) {
                        myPlayerNumber = 1;
                    } else if (p2Url && stringEquals(p2Url, myPlayerName)) {
                        myPlayerNumber = 2;
                    }
                }

                // Deterministic secret word for both LAN duel players
                var wordSeed = seed || this.hashString(sessionId);
                self.pickSecretWord(wordSeed);

                // Register SignalR real-time event handlers
                window.GameHubClient.hub.client.wordDuelProgressReceived = function(data) {
                    self.updateOpponentRadar(data);
                };

                window.GameHubClient.hub.client.wordDuelGameFinished = function(result) {
                    if (result && result.ExtraData) {
                        var d = result.ExtraData;
                        var isWin = (d.winnerId === window.GameHubClient.getConnectionId());
                        self.showGameOverModal(isWin, d.winnerName, d.secretWord, d.attemptsUsed, d.elapsedSeconds);
                    }
                };

                window.GameHubClient.hub.client.opponentLeft = function(data) {
                    if (!isGameOver) {
                        isGameOver = true;
                        window.App.showGameModal({
                            title: "🏆 Victory by Forfeit!",
                            text: data.message || "Opponent disconnected. You win the Word Duel!",
                            isWin: true,
                            onRematch: function() { window.location.href = "../Default.aspx"; }
                        });
                    }
                };
            } else {
                self.pickSecretWord(seed);
            }
        },

        hashString: function(str) {
            var hash = 0;
            for (var i = 0; i < str.length; i++) {
                hash = ((hash << 5) - hash) + str.charCodeAt(i);
                hash |= 0;
            }
            return Math.abs(hash);
        },

        pickSecretWord: function(seed) {
            if (seed !== undefined && !isNaN(seed)) {
                var idx = Math.abs(seed) % TARGET_WORDS.length;
                targetWord = TARGET_WORDS[idx];
            } else {
                var randomIdx = Math.floor(Math.random() * TARGET_WORDS.length);
                targetWord = TARGET_WORDS[randomIdx];
            }
            console.log("[WordDuel] Chamber Target Initialized. Length: " + targetWord.length);
        },

        buildBoard: function() {
            var $grid = $('#wordle-grid');
            $grid.empty();

            for (var r = 0; r < maxAttempts; r++) {
                var $row = $('<div class="wordle-row" data-row="' + r + '"></div>');
                for (var c = 0; c < wordLength; c++) {
                    var $tile = $('<div class="wordle-tile" data-row="' + r + '" data-col="' + c + '"><span class="tile-letter"></span></div>');
                    $row.append($tile);
                }
                $grid.append($row);
            }

            currentRow = 0;
            currentCol = 0;
            currentGuess = [];
            boardGuesses = [];
            isGameOver = false;
            gameStartTime = Date.now();
            revealedGreenHints = {};
            revealedYellowHints = {};
            keyboardKeyStates = {};

            this.updateActiveRowIndicator();
        },

        buildKeyboard: function() {
            var $kb = $('#wordle-keyboard');
            $kb.empty();

            var rows = [
                ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
                ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
                ["ENTER", "Z", "X", "C", "V", "B", "N", "M", "BACKSPACE"]
            ];

            var self = this;
            rows.forEach(function(rowKeys, rIdx) {
                var $row = $('<div class="kb-row"></div>');
                rowKeys.forEach(function(key) {
                    var isSpecial = (key === "ENTER" || key === "BACKSPACE");
                    var label = key;
                    if (key === "BACKSPACE") label = "⌫";

                    var $btn = $('<button type="button" class="kb-key ' + (isSpecial ? 'kb-special' : '') + '" data-key="' + key + '">' + label + '</button>');
                    $btn.on('click', function(e) {
                        e.preventDefault();
                        self.handleKeyInput(key);
                    });
                    $row.append($btn);
                });
                $kb.append($row);
            });
        },

        bindEvents: function() {
            var self = this;

            // Physical Keyboard Listener
            $(window).off('keydown.wordduel').on('keydown.wordduel', function(e) {
                if (isGameOver) return;
                var key = e.key.toUpperCase();

                if (key === "ENTER") {
                    e.preventDefault();
                    self.handleKeyInput("ENTER");
                } else if (key === "BACKSPACE") {
                    e.preventDefault();
                    self.handleKeyInput("BACKSPACE");
                } else if (/^[A-Z]$/.test(key)) {
                    e.preventDefault();
                    self.handleKeyInput(key);
                }
            });

            // Reset / New Word Button
            $('#btn-new-word').on('click', function(e) {
                e.preventDefault();
                self.resetRound();
            });

            // Get Hint / Clue Modal
            $('#btn-get-hint').on('click', function(e) {
                e.preventDefault();
                self.showHintModal();
            });

            // Dismiss Clue Banner
            $('#btn-dismiss-clue').on('click', function(e) {
                e.preventDefault();
                $('#active-clue-banner').slideUp(200);
            });

            // Hard Mode Toggle
            $('#hard-mode-toggle').on('change', function() {
                hardMode = $(this).is(':checked');
                if (window.App) window.App.toast("Hard Mode: " + (hardMode ? "Enabled" : "Disabled"), "info");
            });

            // Stats Modal Trigger
            $('#btn-show-stats').on('click', function(e) {
                e.preventDefault();
                self.showStatsModal();
            });

            // Give Up / Reveal Word
            $('#btn-give-up').on('click', function(e) {
                e.preventDefault();
                if (!isGameOver) {
                    self.concludeGame(false);
                }
            });
        },

        showHintModal: function() {
            var self = this;
            if (isGameOver) return;

            // Compute hints
            var targetArr = targetWord.split('');
            var vowels = ['A', 'E', 'I', 'O', 'U'];
            var foundVowels = [];
            targetArr.forEach(function(ch) {
                if (vowels.indexOf(ch) !== -1 && foundVowels.indexOf(ch) === -1) {
                    foundVowels.push(ch);
                }
            });
            var vowelText = foundVowels.length > 0 ? foundVowels.join(', ') : "No standard vowels";

            var category = self.getWordCategory(targetWord);

            var html = '<div id="hint-modal" class="modal-backdrop active">' +
                '<div class="modal-box" style="max-width: 480px; width: 95%;">' +
                    '<h2 class="modal-title">💡 Mystery Word Deductive Clues</h2>' +
                    '<p class="modal-text">Select which type of clue you want to reveal:</p>' +

                    '<div style="display: flex; flex-direction: column; gap: 10px; margin: 16px 0; text-align: left;">' +
                        '<!-- Option 1: Category -->' +
                        '<button type="button" class="btn btn-outline clue-opt-btn" id="clue-btn-category" style="padding: 12px 14px; display: flex; align-items: center; justify-content: space-between; text-align: left; border-color: #38bdf8;">' +
                            '<div>' +
                                '<strong style="color: #38bdf8; font-size: 0.95rem; display: block;">🏷️ Word Theme / Category</strong>' +
                                '<span style="font-size: 0.75rem; color: #94a3b8;">Reveals the contextual subject area or meaning</span>' +
                            '</div>' +
                            '<span style="font-size: 1.1rem;">👉</span>' +
                        '</button>' +

                        '<!-- Option 2: Vowels Radar -->' +
                        '<button type="button" class="btn btn-outline clue-opt-btn" id="clue-btn-vowels" style="padding: 12px 14px; display: flex; align-items: center; justify-content: space-between; text-align: left; border-color: #fbbf24;">' +
                            '<div>' +
                                '<strong style="color: #fbbf24; font-size: 0.95rem; display: block;">🎯 Vowels Radar</strong>' +
                                '<span style="font-size: 0.75rem; color: #94a3b8;">Reveals which vowels (A, E, I, O, U) exist in this word</span>' +
                            '</div>' +
                            '<span style="font-size: 1.1rem;">👉</span>' +
                        '</button>' +

                        '<!-- Option 3: Starting & Ending Letter -->' +
                        '<button type="button" class="btn btn-outline clue-opt-btn" id="clue-btn-edges" style="padding: 12px 14px; display: flex; align-items: center; justify-content: space-between; text-align: left; border-color: #34d399;">' +
                            '<div>' +
                                '<strong style="color: #34d399; font-size: 0.95rem; display: block;">🔤 Starting &amp; Ending Letters</strong>' +
                                '<span style="font-size: 0.75rem; color: #94a3b8;">Reveals the 1st and 5th letters of the secret word</span>' +
                            '</div>' +
                            '<span style="font-size: 1.1rem;">👉</span>' +
                        '</button>' +

                        '<!-- Option 4: Reveal Letter Tile -->' +
                        '<button type="button" class="btn btn-outline clue-opt-btn" id="clue-btn-reveal-tile" style="padding: 12px 14px; display: flex; align-items: center; justify-content: space-between; text-align: left; border-color: #a855f7;">' +
                            '<div>' +
                                '<strong style="color: #c084fc; font-size: 0.95rem; display: block;">🟩 Reveal 1 Green Letter Spot</strong>' +
                                '<span style="font-size: 0.75rem; color: #94a3b8;">Reveals one correct letter at its exact position</span>' +
                            '</div>' +
                            '<span style="font-size: 1.1rem;">👉</span>' +
                        '</button>' +
                    '</div>' +

                    '<button type="button" class="btn btn-outline" id="close-hint-modal" style="width: 100%;">Close</button>' +
                '</div></div>';

            $('#hint-modal').remove();
            $('body').append(html);

            // Category Clue
            $('#clue-btn-category').on('click', function(e) {
                e.preventDefault();
                $('#hint-modal').remove();
                self.setClueBanner("🏷️ Category: " + category);
                if (window.App) window.App.toast("Clue: Category is '" + category + "'", "info");
            });

            // Vowels Radar
            $('#clue-btn-vowels').on('click', function(e) {
                e.preventDefault();
                $('#hint-modal').remove();
                self.setClueBanner("🎯 Vowels Present: " + vowelText);
                if (window.App) window.App.toast("Vowels present: " + vowelText, "info");
            });

            // Starting & Ending Letters
            $('#clue-btn-edges').on('click', function(e) {
                e.preventDefault();
                $('#hint-modal').remove();
                var edgeText = "Starts with '" + targetArr[0] + "' and ends with '" + targetArr[wordLength - 1] + "'";
                self.setClueBanner("🔤 Word Structure: " + edgeText);
                if (window.App) window.App.toast(edgeText, "info");
            });

            // Reveal 1 Green Tile
            $('#clue-btn-reveal-tile').on('click', function(e) {
                e.preventDefault();
                $('#hint-modal').remove();
                // Find an unrevealed index
                var unrevealed = [];
                for (var i = 0; i < wordLength; i++) {
                    if (!revealedGreenHints[i]) unrevealed.push(i);
                }
                var pickIdx = unrevealed.length > 0 ? unrevealed[Math.floor(Math.random() * unrevealed.length)] : 0;
                var letter = targetArr[pickIdx];
                revealedGreenHints[pickIdx] = letter;

                self.setClueBanner("🟩 Spot Reveal: Letter #" + (pickIdx + 1) + " is '" + letter + "'");
                self.updateKeyboardKey(letter, 'correct');
                if (window.App) window.App.toast("Letter #" + (pickIdx + 1) + " is '" + letter + "'!", "success");
            });

            $('#close-hint-modal').on('click', function(e) {
                e.preventDefault();
                $('#hint-modal').remove();
            });
        },

        setClueBanner: function(text) {
            $('#active-clue-text').text("💡 " + text);
            $('#active-clue-banner').slideDown(200);
        },

        getWordCategory: function(word) {
            var w = (word || '').toUpperCase();
            var categories = {
                // Animals / Living Beings
                "BEAST": "Animals & Wildlife", "CAMEL": "Animals & Wildlife", "HORSE": "Animals & Wildlife", "SHARK": "Ocean Predator", "SHEEP": "Farm Animals", "SNAKE": "Reptiles", "TIGER": "Big Cats / Wild Predator", "ZEBRA": "African Wildlife", "HOUND": "Canine / Dog", "EAGLE": "Birds of Prey", "GIRAFFE": "Tall African Wildlife", "PUPPY": "Cute Pets", "ROBIN": "Songbird", "WHALE": "Marine Mammal", "SKUNK": "Woodland Creature",
                // Nature & Geography
                "BEACH": "Coast & Ocean", "CLIFF": "Landscapes & Rocks", "CLOUD": "Sky & Atmosphere", "CREEK": "Streams & Rivers", "EARTH": "Planet & Nature", "FLORA": "Plants & Flowers", "FROST": "Cold Weather & Ice", "GRASS": "Lawn & Nature", "GROVE": "Forest & Trees", "OCEAN": "Deep Seas & Waters", "RIVER": "Waterways & Geography", "STORM": "Weather & Thunder", "WINDY": "Breezy Weather", "WINTER": "Cold Season", "VALLEY": "Geography & Mountains", "DESERT": "Arid Land & Sand", "ISLAND": "Land Surrounded by Water",
                // Food & Cuisine
                "APPLE": "Fresh Fruit", "BREAD": "Bakery & Food", "CANDY": "Sweet Confections", "CREAM": "Dairy & Desserts", "FEAST": "Dining & Celebration", "FLOUR": "Baking Ingredient", "FRUIT": "Natural Sweets", "GRAPE": "Vine Fruit / Wine", "HONEY": "Sweet Bee Nectar", "JUICE": "Fresh Beverage", "LEMON": "Citrus Fruit", "MELON": "Summer Fruit", "PEACH": "Sweet Stone Fruit", "PIZZA": "Italian Cuisine", "SALAD": "Healthy Greens", "SUGAR": "Sweetener", "TOAST": "Breakfast Bread", "WHEAT": "Grain & Agriculture", "BACON": "Breakfast Meat", "CHEESE": "Dairy Food", "BUTTER": "Dairy Spread",
                // Action & Movement
                "CATCH": "Action / Sport", "CLIMB": "Ascending / Movement", "CRAWL": "Movement on Hands & Knees", "DANCE": "Rhythm & Music", "DRIVE": "Vehicles & Transport", "FIGHT": "Combat & Action", "MARCH": "Parade / Walking", "REACH": "Extending & Touching", "SLIDE": "Smooth Motion", "SPEAK": "Communication & Voice", "STAND": "Posture & Balance", "TOUCH": "Physical Contact", "WRITE": "Text & Authorship", "JUMPS": "Leaping & Air Motion",
                // Technology & Computing
                "AUDIO": "Sound & Acoustics", "CYBER": "Computers & Internet", "DIGIT": "Numbers & Computing", "DRONE": "Robotic Aerial Vehicle", "INDEX": "Data & Search", "INPUT": "User Interaction & Keyboards", "LASER": "Focused Optical Light", "LOGIC": "Reasoning & Algorithms", "MICRO": "Tiny / Microelectronics", "MODEM": "Network Hardware", "MOTOR": "Engines & Mechanics", "PIXEL": "Digital Screen Display", "RADAR": "Detection & Waves", "RADIO": "Broadcast Transmission", "ROBOT": "Automation & Machines", "SONIC": "High Speed / Sound", "TURBO": "Boosted Speed & Power", "VIDEO": "Visual Motion Display",
                // Security & Combat
                "GUARD": "Protection, Security & Defense", "ARMOR": "Protective Combat Gear", "BLADE": "Sharp Cutting Weapon", "SHIELD": "Defensive Barrier", "SWORD": "Medieval Weapon", "ARROW": "Archery Projectile", "KNIFE": "Cutting Utensil / Tool", "VAULT": "Secure Storage", "SENTRY": "Watchman / Lookout",
                // Emotions & Virtues
                "ANGRY": "Furious Emotion", "BRAIN": "Intellect & Mind", "BRAVE": "Courageous & Bold", "DREAM": "Sleep Visions & Hopes", "FAITH": "Belief & Trust", "GRAVE": "Serious / Resting Place", "GREED": "Desire for Wealth", "GRIEF": "Deep Sorrow", "GUILT": "Remorse & Conscience", "HEART": "Core Emotion / Vital Organ", "HONOR": "Respect & Dignity", "LUCKY": "Fortunate & Blessed", "MAGIC": "Sorcery & Illusions", "MERCY": "Compassion & Forgiveness", "MORAL": "Ethics & Principles", "MUSIC": "Melody & Harmony", "PEACE": "Calm & Tranquility", "PRIDE": "Self-Esteem & Glory", "SMART": "Intelligent & Clever", "TRUTH": "Honesty & Facts"
            };

            if (categories[w]) return categories[w];

            // Structural / Grammatical categorization
            var vowels = ['A', 'E', 'I', 'O', 'U'];
            var count = 0;
            for (var i = 0; i < w.length; i++) {
                if (vowels.indexOf(w[i]) !== -1) count++;
            }
            return "General English Vocabulary (" + count + " Vowels, Starts with '" + w.charAt(0) + "')";
        },

        handleKeyInput: function(key) {
            if (isGameOver) return;

            if (key === "BACKSPACE") {
                if (currentCol > 0) {
                    currentCol--;
                    currentGuess.pop();
                    this.updateTileLetter(currentRow, currentCol, "");
                    if (window.GameAudio && window.GameAudio.playKeyType) window.GameAudio.playKeyType();
                }
            } else if (key === "ENTER") {
                if (currentCol === wordLength) {
                    this.submitGuess();
                } else {
                    this.shakeCurrentRow();
                    if (window.GameAudio && window.GameAudio.playWordInvalid) window.GameAudio.playWordInvalid();
                    if (window.App) window.App.toast("Not enough letters (need " + wordLength + ")", "warning");
                }
            } else if (/^[A-Z]$/.test(key)) {
                if (currentCol < wordLength) {
                    currentGuess.push(key);
                    this.updateTileLetter(currentRow, currentCol, key);
                    this.popTile(currentRow, currentCol);
                    currentCol++;
                    if (window.GameAudio && window.GameAudio.playKeyType) window.GameAudio.playKeyType();
                }
            }
        },

        updateTileLetter: function(r, c, char) {
            var $tile = $('.wordle-tile[data-row="' + r + '"][data-col="' + c + '"]');
            $tile.find('.tile-letter').text(char);
            if (char) {
                $tile.addClass('tile-filled');
            } else {
                $tile.removeClass('tile-filled');
            }
        },

        popTile: function(r, c) {
            var $tile = $('.wordle-tile[data-row="' + r + '"][data-col="' + c + '"]');
            $tile.addClass('tile-pop');
            setTimeout(function() {
                $tile.removeClass('tile-pop');
            }, 120);
        },

        shakeCurrentRow: function() {
            var $row = $('.wordle-row[data-row="' + currentRow + '"]');
            $row.addClass('row-shake');
            setTimeout(function() {
                $row.removeClass('row-shake');
            }, 500);
        },

        danceCurrentRow: function() {
            var self = this;
            $('.wordle-row[data-row="' + currentRow + '"] .wordle-tile').each(function(idx) {
                var $tile = $(this);
                setTimeout(function() {
                    $tile.addClass('tile-dance');
                }, idx * 100);
            });
        },

        submitGuess: function() {
            var guessWord = currentGuess.join('');

            // 1. Vocabulary Lookup Guard
            if (!VALID_WORDS_SET[guessWord]) {
                this.shakeCurrentRow();
                if (window.GameAudio && window.GameAudio.playWordInvalid) window.GameAudio.playWordInvalid();
                if (window.App) window.App.toast("'" + guessWord + "' is not in the word list!", "error");
                return;
            }

            // 2. Hard Mode Validation Guard
            if (hardMode && currentRow > 0) {
                // Must use all revealed green letters at exact spots
                for (var gIdx in revealedGreenHints) {
                    var idxNum = parseInt(gIdx, 10);
                    if (currentGuess[idxNum] !== revealedGreenHints[gIdx]) {
                        this.shakeCurrentRow();
                        if (window.App) window.App.toast("Hard Mode: Letter " + (idxNum + 1) + " must be '" + revealedGreenHints[gIdx] + "'!", "warning");
                        return;
                    }
                }
                // Must contain all yellow letters
                for (var yChar in revealedYellowHints) {
                    if (currentGuess.indexOf(yChar) === -1) {
                        this.shakeCurrentRow();
                        if (window.App) window.App.toast("Hard Mode: Guess must contain '" + yChar + "'!", "warning");
                        return;
                    }
                }
            }

            // 3. Two-Pass Exact vs Frequency Evaluation
            var targetArr = targetWord.split('');
            var guessArr = currentGuess.slice();
            var rowResult = ['absent', 'absent', 'absent', 'absent', 'absent'];
            var targetLetterCounts = {};

            // Pass 1: Match Exact Greens
            for (var i = 0; i < wordLength; i++) {
                var tChar = targetArr[i];
                targetLetterCounts[tChar] = (targetLetterCounts[tChar] || 0) + 1;
            }

            for (var i = 0; i < wordLength; i++) {
                if (guessArr[i] === targetArr[i]) {
                    rowResult[i] = 'correct'; // Green
                    targetLetterCounts[guessArr[i]]--;
                    revealedGreenHints[i] = guessArr[i];
                }
            }

            // Pass 2: Match Yellows and Grays
            for (var i = 0; i < wordLength; i++) {
                if (rowResult[i] === 'correct') continue;
                var gChar = guessArr[i];
                if (targetLetterCounts[gChar] && targetLetterCounts[gChar] > 0) {
                    rowResult[i] = 'present'; // Yellow
                    targetLetterCounts[gChar]--;
                    revealedYellowHints[gChar] = true;
                } else {
                    rowResult[i] = 'absent'; // Gray
                }
            }

            boardGuesses.push({ word: guessWord, result: rowResult });

            // 4. Animate 3D Tile Flip Reveal
            var self = this;
            var isSolved = (guessWord === targetWord);

            for (var c = 0; c < wordLength; c++) {
                (function(colIdx, state, letter) {
                    var $tile = $('.wordle-tile[data-row="' + currentRow + '"][data-col="' + colIdx + '"]');
                    setTimeout(function() {
                        $tile.addClass('tile-flip');
                        setTimeout(function() {
                            $tile.addClass('tile-' + state);
                            if (window.GameAudio && window.GameAudio.playLetterFlip) {
                                window.GameAudio.playLetterFlip(colIdx);
                            }
                            self.updateKeyboardKey(letter, state);
                        }, 250);
                    }, colIdx * 200);
                })(c, rowResult[c], guessArr[c]);
            }

            // 5. Multiplayer Progress Telemetry Sync
            if (isMultiplayer && window.GameHubClient.isConnected()) {
                var pattern = rowResult.map(function(s) {
                    if (s === 'correct') return 'G';
                    if (s === 'present') return 'Y';
                    return 'A';
                });
                window.GameHubClient.hub.server.sendWordDuelProgress(sessionId, {
                    row: currentRow,
                    pattern: pattern,
                    attempts: currentRow + 1,
                    solved: isSolved
                });
            }

            // 6. Post-Reveal Win/Loss Evaluation
            setTimeout(function() {
                if (isSolved) {
                    self.danceCurrentRow();
                    self.concludeGame(true);
                } else if (currentRow >= maxAttempts - 1) {
                    self.concludeGame(false);
                } else {
                    currentRow++;
                    currentCol = 0;
                    currentGuess = [];
                    self.updateActiveRowIndicator();
                }
            }, wordLength * 200 + 400);
        },

        updateKeyboardKey: function(letter, state) {
            var currentPriority = { 'correct': 3, 'present': 2, 'absent': 1, '': 0 };
            var existingState = keyboardKeyStates[letter] || '';

            if (currentPriority[state] > currentPriority[existingState]) {
                keyboardKeyStates[letter] = state;
                var $key = $('.kb-key[data-key="' + letter + '"]');
                $key.removeClass('kb-correct kb-present kb-absent').addClass('kb-' + state);
            }
        },

        updateActiveRowIndicator: function() {
            $('.wordle-row').removeClass('active-row');
            $('.wordle-row[data-row="' + currentRow + '"]').addClass('active-row');
            $('#guess-count-badge').text((currentRow + 1) + ' / ' + maxAttempts);
        },

        concludeGame: function(isWin) {
            if (isGameOver) return;
            isGameOver = true;

            var elapsedSeconds = Math.max(Math.floor((Date.now() - gameStartTime) / 1000), 1);
            var attemptsUsed = isWin ? (currentRow + 1) : maxAttempts;

            this.recordStats(isWin, attemptsUsed);

            if (isWin && window.GameAudio && window.GameAudio.playWordVictory) {
                window.GameAudio.playWordVictory();
            } else if (!isWin && window.GameAudio && window.GameAudio.playWordInvalid) {
                window.GameAudio.playWordInvalid();
            }

            if (isMultiplayer && window.GameHubClient.isConnected()) {
                window.GameHubClient.hub.server.finishWordDuelGame(sessionId, targetWord, attemptsUsed, elapsedSeconds);
            } else {
                var self = this;
                setTimeout(function() {
                    self.showGameOverModal(isWin, myPlayerName, targetWord, attemptsUsed, elapsedSeconds);
                }, 600);
            }
        },

        updateOpponentRadar: function(data) {
            if (!data) return;
            var r = data.row;
            var pattern = data.pattern || [];

            var $oppRow = $('#opp-row-' + r);
            if ($oppRow.length === 0) {
                $oppRow = $('<div class="opp-radar-row" id="opp-row-' + r + '"></div>');
                $('#opponent-radar-grid').append($oppRow);
            }
            $oppRow.empty();

            pattern.forEach(function(code) {
                var colorClass = (code === 'G') ? 'opp-correct' : (code === 'Y' ? 'opp-present' : 'opp-absent');
                $oppRow.append('<div class="opp-radar-tile ' + colorClass + '"></div>');
            });

            $('#opponent-radar-attempts').text('Attempts: ' + (data.attempts || (r + 1)) + ' / ' + maxAttempts);
            if (data.solved) {
                $('#opponent-radar-status').text('Status: Cracked the Word! ⚡').css('color', '#34d399');
            }
        },

        recordStats: function(isWin, attempts) {
            var stats = this.getStats();
            stats.played++;
            if (isWin) {
                stats.won++;
                stats.streak++;
                stats.maxStreak = Math.max(stats.maxStreak, stats.streak);
                stats.distribution[attempts] = (stats.distribution[attempts] || 0) + 1;
            } else {
                stats.streak = 0;
            }
            localStorage.setItem('wordduel_stats', JSON.stringify(stats));
            this.updateStatsDisplay();
        },

        getStats: function() {
            var defaultStats = {
                played: 0,
                won: 0,
                streak: 0,
                maxStreak: 0,
                distribution: { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0 }
            };
            try {
                var raw = localStorage.getItem('wordduel_stats');
                return raw ? JSON.parse(raw) : defaultStats;
            } catch (e) {
                return defaultStats;
            }
        },

        updateStatsDisplay: function() {
            var stats = this.getStats();
            var winRate = stats.played > 0 ? Math.round((stats.won / stats.played) * 100) : 0;
            $('#stat-played').text(stats.played);
            $('#stat-winrate').text(winRate + '%');
            $('#stat-streak').text(stats.streak);
            $('#stat-maxstreak').text(stats.maxStreak);
        },

        showStatsModal: function() {
            var stats = this.getStats();
            var winRate = stats.played > 0 ? Math.round((stats.won / stats.played) * 100) : 0;
            var maxDist = 1;
            for (var k in stats.distribution) {
                if (stats.distribution[k] > maxDist) maxDist = stats.distribution[k];
            }

            var distHtml = '<div style="margin-top: 14px; text-align: left;">' +
                '<h4 style="color: #38bdf8; font-size: 0.85rem; margin-bottom: 8px; text-transform: uppercase;">Guess Distribution</h4>';

            for (var i = 1; i <= 6; i++) {
                var count = stats.distribution[i] || 0;
                var pct = Math.max(Math.round((count / maxDist) * 100), 8);
                distHtml += '<div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px; font-size: 0.8rem;">' +
                    '<span style="width: 14px; font-weight: 700;">' + i + '</span>' +
                    '<div style="flex: 1; background: #1e293b; border-radius: 4px; overflow: hidden;">' +
                        '<div style="width: ' + pct + '%; background: ' + (count > 0 ? '#34d399' : '#334155') + '; color: #fff; padding: 2px 6px; font-weight: 800; font-size: 0.75rem; text-align: right;">' + count + '</div>' +
                    '</div>' +
                '</div>';
            }
            distHtml += '</div>';

            var modalHtml = '<div style="background: rgba(15,23,42,0.8); border: 1px solid #334155; border-radius: 12px; padding: 14px; margin: 12px 0;">' +
                '<div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; text-align: center;">' +
                    '<div><strong style="color: #38bdf8; font-size: 1.2rem;">' + stats.played + '</strong><div style="font-size: 0.7rem; opacity: 0.8;">Played</div></div>' +
                    '<div><strong style="color: #34d399; font-size: 1.2rem;">' + winRate + '%</strong><div style="font-size: 0.7rem; opacity: 0.8;">Win Rate</div></div>' +
                    '<div><strong style="color: #fbbf24; font-size: 1.2rem;">' + stats.streak + '</strong><div style="font-size: 0.7rem; opacity: 0.8;">Streak</div></div>' +
                    '<div><strong style="color: #f43f5e; font-size: 1.2rem;">' + stats.maxStreak + '</strong><div style="font-size: 0.7rem; opacity: 0.8;">Max Streak</div></div>' +
                '</div>' +
                distHtml +
            '</div>';

            window.App.showGameModal({
                title: "📊 Vocabulary Analytics",
                text: "Your Wordle deductive performance record:",
                html: modalHtml,
                isWin: true,
                onRematch: function() {}
            });
        },

        showGameOverModal: function(isWin, winnerName, secretWord, attemptsUsed, elapsedSeconds) {
            var self = this;
            var summaryHtml = '<div style="background: rgba(15,23,42,0.85); border: 1px solid #334155; border-radius: 12px; padding: 16px; margin: 14px 0; text-align: left;">' +
                '<div style="text-align: center; margin-bottom: 12px;">' +
                    '<span style="font-size: 0.8rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 1px;">Secret Word</span>' +
                    '<div style="font-size: 1.8rem; font-weight: 900; color: #34d399; letter-spacing: 4px; margin-top: 2px;">' + secretWord + '</div>' +
                '</div>' +
                '<div style="display: flex; justify-content: space-between; margin-bottom: 6px; font-size: 0.9rem;"><span>Guesses Used:</span><strong style="color: #38bdf8;">' + (isWin ? (attemptsUsed + ' / ' + maxAttempts) : 'X / ' + maxAttempts) + '</strong></div>' +
                '<div style="display: flex; justify-content: space-between; font-size: 0.9rem;"><span>Solve Time:</span><strong style="color: #fbbf24;">' + elapsedSeconds + 's</strong></div>' +
            '</div>';

            var modalText = isWin
                ? ("Splendid deduction! You unmasked the secret word!" + summaryHtml)
                : ("Chamber locked! The mystery word was " + secretWord + "." + summaryHtml);

            window.App.showGameModal({
                title: isWin ? "🏆 Word Master Victory!" : "⚡ Round Concluded",
                text: modalText,
                html: modalText,
                isWin: isWin,
                onRematch: function() {
                    self.resetRound();
                }
            });
        },

        resetRound: function() {
            this.pickSecretWord();
            this.buildBoard();
            this.buildKeyboard();
            $('#opponent-radar-grid').empty();
            $('#opponent-radar-status').text('Status: Decrypting...');
            $('#opponent-radar-attempts').text('Attempts: 0 / 6');
        }
    };

    function stringEquals(a, b) {
        return (a || '').toLowerCase() === (b || '').toLowerCase();
    }

    $(document).ready(function() {
        WordDuel.init();
    });

    window.WordDuel = WordDuel;

})(window, jQuery);
