//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHub.Games
{
    public partial class Game2048Page
    {
    }
}
